services:
  ibc-swap-client:
    build:
      context: ..
      dockerfile: dapps/ibc-swap/client/Dockerfile
    init: true
    restart: unless-stopped
    ports:
      - "${IBC_SWAP_HOST_PORT:-3000}:3000"
    environment:
      BASE_PATH: ${IBC_SWAP_BASE_PATH:-}
      NEXT_PUBLIC_ENTRYPOINT_RPC_ENDPOINT: ${IBC_SWAP_ENTRYPOINT_RPC_ENDPOINT:-http://localhost:26657}
      NEXT_PUBLIC_ENTRYPOINT_REST_ENDPOINT: ${IBC_SWAP_ENTRYPOINT_REST_ENDPOINT:-http://localhost:1317}
      NEXT_PUBLIC_LOCALOSMOIS_RPC_ENDPOINT: ${IBC_SWAP_LOCALOSMOSIS_RPC_ENDPOINT:-http://localhost:26658}
      NEXT_PUBLIC_LOCALOSMOIS_REST_ENDPOINT: ${IBC_SWAP_LOCALOSMOSIS_REST_ENDPOINT:-http://localhost:1318}
      NEXT_PUBLIC_CROSSCHAIN_SWAP_ADDRESS: ${IBC_SWAP_CROSSCHAIN_SWAP_ADDRESS:-}
      NEXT_PUBLIC_GATEWAY_TX_BUILDER_ENDPOINT: ${IBC_SWAP_GATEWAY_ENDPOINT:-http://localhost:8000}
      NEXT_PUBLIC_CARDANO_CHAIN_ID: ${IBC_SWAP_CARDANO_CHAIN_ID:-42}
      NEXT_PUBLIC_BLOCKFROST_PROJECT_ID: ${IBC_SWAP_BLOCKFROST_PROJECT_ID:-}
      NEXT_PUBLIC_KUPMIOS_URL: ${IBC_SWAP_KUPMIOS_URL:-http://localhost:1442,http://localhost:1337}
      NEXT_PUBLIC_FORWARD_TIMEOUT: ${IBC_SWAP_FORWARD_TIMEOUT:-60m}

  ibc-explorer:
    build:
      context: ./ibc-explorer
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    ports:
      - "${IBC_EXPLORER_HOST_PORT:-8081}:8080"
    environment:
      PORT: "8080"
      REACT_APP_API_DOMAIN: ${IBC_EXPLORER_GRAPHQL_ENDPOINT:-http://localhost:3001/v1/graphql}
      REACT_APP_CARDANO_CHAIN_ID: ${IBC_EXPLORER_CARDANO_CHAIN_ID:-42}
      REACT_APP_ENTRYPOINT_RPC_ENDPOINT: ${IBC_EXPLORER_ENTRYPOINT_RPC_ENDPOINT:-http://localhost:26657}
      REACT_APP_ENTRYPOINT_REST_ENDPOINT: ${IBC_EXPLORER_ENTRYPOINT_REST_ENDPOINT:-http://localhost:1317}
      REACT_APP_LOCALOSMOIS_RPC_ENDPOINT: ${IBC_EXPLORER_LOCALOSMOSIS_RPC_ENDPOINT:-http://localhost:26658}
      REACT_APP_LOCALOSMOIS_REST_ENDPOINT: ${IBC_EXPLORER_LOCALOSMOSIS_REST_ENDPOINT:-http://localhost:1318}
