store.cardano.host=${CARDANO_CHAIN_HOST:cardano-node}
store.cardano.port=${CARDANO_CHAIN_PORT:3001}
store.cardano.protocol-magic=${CARDANO_CHAIN_NETWORK_MAGIC:42}
store.cardano.byron-genesis-file=/app/genesis/genesis-byron.json
store.cardano.shelley-genesis-file=/app/genesis/genesis-shelley.json
store.cardano.alonzo-genesis-file=/app/genesis/genesis-alonzo.json
store.cardano.conway-genesis-file=/app/genesis/genesis-conway.json

spring.datasource.url=jdbc:postgresql://${HISTORY_DB_HOST:yaci-store-postgres}:${HISTORY_DB_PORT:5432}/${HISTORY_DB_NAME:yaci_store}
spring.datasource.username=${HISTORY_DB_USERNAME:yaci}
spring.datasource.password=${HISTORY_DB_PASSWORD:dbpass}
spring.datasource.hikari.maximum-pool-size=20

logging.file.name=/app/logs/yaci-store.log
apiPrefix=/api/v1

store.transaction.save-cbor=true
store.blocks.save-cbor=false

store.assets.enabled=false
store.metadata.enabled=false
store.mir.enabled=false
store.governance.enabled=false
store.epoch.enabled=true

store.blocks.enabled=true
store.script.enabled=true
store.staking.enabled=true
store.transaction.enabled=true
store.utxo.enabled=true

store.executor.enable-parallel-processing=true
store.executor.blocks-batch-size=50
store.executor.blocks-partition-size=10

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
