[[chains]]
id = 'injective-777'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:26660'
grpc_addr = 'http://127.0.0.1:9097'
event_source = { mode = 'push', url = 'ws://127.0.0.1:26660/websocket', batch_delay = '200ms' }
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'inj'
key_name = 'injective-local-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0.1, denom = 'stake' }
gas_multiplier = 2.0
max_msg_num = 20
max_tx_size = 209715
clock_drift = '20s'
max_block_time = '10s'
trusting_period = '10days'
memo_prefix = 'Caribic'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'injective-888'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:26659'
grpc_addr = 'http://127.0.0.1:9096'
event_source = { mode = 'push', url = 'ws://127.0.0.1:26659/websocket', batch_delay = '200ms' }
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'inj'
key_name = 'injective-888-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0.025, denom = 'inj' }
gas_multiplier = 1.8
max_msg_num = 20
max_tx_size = 209715
clock_drift = '20s'
max_block_time = '10s'
trusting_period = '10days'
memo_prefix = 'Caribic'
trust_threshold = { numerator = '1', denominator = '3' }
