services:
  mithril-aggregator:
    image: ${MITHRIL_AGGREGATOR_IMAGE}
    user: "${UID:-1000}:${GID:-1000}"
    restart: always
    profiles:
      - mithril
    volumes:
      - ${CARDANO_NODE_DIR}:/data:z
      - ${MITHRIL_DATA_DIR}:/mithril:z
    networks:
      - mithril_network
    ports:
      - "8080:8080"
    environment:
      - RUST_BACKTRACE=1
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=
      - NETWORK=devnet
      - NETWORK_MAGIC=42
      - PROTOCOL_PARAMETERS__K=3
      - PROTOCOL_PARAMETERS__M=50
      - PROTOCOL_PARAMETERS__PHI_F=0.67
      - RUN_INTERVAL=1000
      - URL_SNAPSHOT_MANIFEST=
      - SNAPSHOT_STORE_TYPE=local
      - SNAPSHOT_UPLOADER_TYPE=local
      - SNAPSHOT_COMPRESSION_ALGORITHM=zstandard
      - DATA_STORES_DIRECTORY=/mithril/aggregator/stores
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket
      - CARDANO_NODE_VERSION=${CARDANO_NODE_VERSION}
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
      - CHAIN_OBSERVER_TYPE=${CHAIN_OBSERVER_TYPE}
      - GENESIS_VERIFICATION_KEY=${GENESIS_VERIFICATION_KEY}
      - DB_DIRECTORY=/data/db
      - SNAPSHOT_DIRECTORY=/mithril/aggregator
      - SERVER_PORT=8080
      - SIGNED_ENTITY_TYPES=CardanoTransactions
      - CURRENT_ERA_EPOCH=0
      - ERA_ADAPTER_TYPE=bootstrap
      - CARDANO_TRANSACTIONS_SIGNING_CONFIG__STEP=5
      - CARDANO_TRANSACTIONS_SIGNING_CONFIG__SECURITY_PARAMETER=15
    command:
      [
        "-vvv",
        "serve"
      ]

  mithril-aggregator-genesis:
    image: ${MITHRIL_AGGREGATOR_IMAGE}
    user: "${UID:-1000}:${GID:-1000}"
    profiles:
      - mithril-genesis
    volumes:
      - ${CARDANO_NODE_DIR}:/data:z
      - ${MITHRIL_DATA_DIR}:/mithril:z
    networks:
    - mithril_network
    ports:
      - "8080:8080"
    environment:
      - RUST_BACKTRACE=1
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=
      - NETWORK=devnet
      - NETWORK_MAGIC=42
      - PROTOCOL_PARAMETERS__K=3
      - PROTOCOL_PARAMETERS__M=50
      - PROTOCOL_PARAMETERS__PHI_F=0.67
      - RUN_INTERVAL=1000
      - URL_SNAPSHOT_MANIFEST=
      - SNAPSHOT_STORE_TYPE=local
      - SNAPSHOT_UPLOADER_TYPE=local
      - SNAPSHOT_COMPRESSION_ALGORITHM=zstandard
      - DATA_STORES_DIRECTORY=/mithril/aggregator/stores
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket
      - CARDANO_NODE_VERSION=${CARDANO_NODE_VERSION}
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
      - CHAIN_OBSERVER_TYPE=${CHAIN_OBSERVER_TYPE}
      - GENESIS_VERIFICATION_KEY=${GENESIS_VERIFICATION_KEY}
      - GENESIS_SECRET_KEY=${GENESIS_SECRET_KEY}
      - DB_DIRECTORY=/data/db
      - SNAPSHOT_DIRECTORY=/mithril/aggregator
      - SERVER_PORT=8080
      - SIGNED_ENTITY_TYPES=CardanoTransactions
      - CURRENT_ERA_EPOCH=0
      - ERA_ADAPTER_TYPE=bootstrap
      - CARDANO_TRANSACTIONS_SIGNING_CONFIG__STEP=5
      - CARDANO_TRANSACTIONS_SIGNING_CONFIG__SECURITY_PARAMETER=15
    command:
      [
        "-vvv",
        "genesis",
        "bootstrap"
      ]
  mithril-signer-1:
    image: ${MITHRIL_SIGNER_IMAGE}
    user: "${UID:-1000}:${GID:-1000}"
    restart: always
    profiles:
      - mithril
    volumes:
      - ${CARDANO_NODE_DIR}:/data:z
      - ${MITHRIL_DATA_DIR}:/mithril:z
    networks:
    - mithril_network
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=devnet
      - NETWORK_MAGIC=42
      - RUN_INTERVAL=1000
      - DB_DIRECTORY=/data/db
      - DATA_STORES_DIRECTORY=/mithril/signer-1/stores
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
      - KES_SECRET_KEY_PATH=/data/kes.skey
      - OPERATIONAL_CERTIFICATE_PATH=/data/opcert.cert
      - SIGNED_ENTITY_TYPES=CardanoTransactions
    command:
      [
        "-vvv"
      ]

  mithril-signer-2:
    image: ${MITHRIL_SIGNER_IMAGE}
    user: "${UID:-1000}:${GID:-1000}"
    restart: always
    profiles:
      - mithril
    volumes:
      - ${CARDANO_NODE_DIR}:/data:z
      - ${MITHRIL_DATA_DIR}:/mithril:z
    networks:
    - mithril_network
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=devnet
      - NETWORK_MAGIC=42
      - RUN_INTERVAL=1000
      - DB_DIRECTORY=/data/db
      - DATA_STORES_DIRECTORY=/mithril/signer-2/stores
      - CARDANO_NODE_SOCKET_PATH=/data/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
      - KES_SECRET_KEY_PATH=/data/kes.skey
      - OPERATIONAL_CERTIFICATE_PATH=/data/opcert.cert
      - SIGNED_ENTITY_TYPES=CardanoTransactions
    command:
      [
        "-vvv"
      ]

networks:
  mithril_network:
    driver: bridge
  cardano_network:
    driver: bridge
    
