pub const max_chain_id_len = 50

pub const tm_hash_size = 32

pub const max_consensus_state_size = 300

// 20 hex bytes
pub const address_size = 20

pub const max_signature_size = 64

pub const batch_verify_threshold = 2

pub const block_id_flag_unknown = 0

pub const block_id_flag_absent = 1

pub const block_id_flag_commit = 2

pub const block_id_flag_nil = 3

pub const unknown_type = 0

pub const prevote_type = 1

pub const precommit_type = 2

pub const proposal_type = 32
