[workspace]
resolver = "2"
members = [
  'contracts/*',
]

[workspace.package]
version = "0.1.0"
authors = ["Nicolas Lara <nicolaslara@gmail.com>"]
edition = "2021"
rust-version  = "1.81.0"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[workspace.dependencies]
cosmwasm-schema = "2.1.4"
cosmwasm-std = { version = "2.1.4", features = ["stargate"] }
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
schemars = "0.8.22"
osmosis-std = "0.27.0"
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.69" }
cw-multi-test = { version = "2.2.0", features = ["stargate"] }
osmosis-testing = { package = "osmosis-test-tube", version = "27.0.1" }
serde-json-wasm = "1.0.1"
serde-cw-value = "0.7.0"
bech32 = "0.9.1"
cw-utils = "2.0.0"
