// Code generated by scripts/ci/generate-light-client-models.mjs. DO NOT EDIT.

package state

import "time"

type Height struct {
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	RevisionHeight uint64 `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
}

type StakeDistributionEntry struct {
	PoolId                   string `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Stake                    uint64 `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	VrfKeyHash               []byte `protobuf:"bytes,3,opt,name=vrf_key_hash,json=vrfKeyHash,proto3" json:"vrf_key_hash,omitempty"`
	FirstRegistrationSlot    uint64 `protobuf:"varint,4,opt,name=first_registration_slot,json=firstRegistrationSlot,proto3" json:"first_registration_slot,omitempty"`
	RelativeStakeNumerator   uint64 `protobuf:"varint,5,opt,name=relative_stake_numerator,json=relativeStakeNumerator,proto3" json:"relative_stake_numerator,omitempty"`
	RelativeStakeDenominator uint64 `protobuf:"varint,6,opt,name=relative_stake_denominator,json=relativeStakeDenominator,proto3" json:"relative_stake_denominator,omitempty"`
}

type EpochContext struct {
	Epoch                 uint64                    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	StakeDistribution     []*StakeDistributionEntry `protobuf:"bytes,2,rep,name=stake_distribution,json=stakeDistribution,proto3" json:"stake_distribution,omitempty"`
	EpochNonce            []byte                    `protobuf:"bytes,3,opt,name=epoch_nonce,json=epochNonce,proto3" json:"epoch_nonce,omitempty"`
	SlotsPerKesPeriod     uint64                    `protobuf:"varint,4,opt,name=slots_per_kes_period,json=slotsPerKesPeriod,proto3" json:"slots_per_kes_period,omitempty"`
	EpochStartSlot        uint64                    `protobuf:"varint,5,opt,name=epoch_start_slot,json=epochStartSlot,proto3" json:"epoch_start_slot,omitempty"`
	EpochEndSlotExclusive uint64                    `protobuf:"varint,6,opt,name=epoch_end_slot_exclusive,json=epochEndSlotExclusive,proto3" json:"epoch_end_slot_exclusive,omitempty"`
}

type OperationalCertificateCounter struct {
	PoolId         []byte `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
}

type ClientState struct {
	ChainId                                         string                           `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	LatestHeight                                    *Height                          `protobuf:"bytes,2,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	FrozenHeight                                    *Height                          `protobuf:"bytes,3,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	CurrentEpoch                                    uint64                           `protobuf:"varint,4,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	TrustingPeriod                                  time.Duration                    `protobuf:"bytes,5,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	UpgradePath                                     []string                         `protobuf:"bytes,7,rep,name=upgrade_path,json=upgradePath,proto3" json:"upgrade_path,omitempty"`
	HostStateNftPolicyId                            []byte                           `protobuf:"bytes,8,opt,name=host_state_nft_policy_id,json=hostStateNftPolicyId,proto3" json:"host_state_nft_policy_id,omitempty"`
	HostStateNftTokenName                           []byte                           `protobuf:"bytes,9,opt,name=host_state_nft_token_name,json=hostStateNftTokenName,proto3" json:"host_state_nft_token_name,omitempty"`
	EpochStakeDistribution                          []*StakeDistributionEntry        `protobuf:"bytes,10,rep,name=epoch_stake_distribution,json=epochStakeDistribution,proto3" json:"epoch_stake_distribution,omitempty"`
	EpochNonce                                      []byte                           `protobuf:"bytes,11,opt,name=epoch_nonce,json=epochNonce,proto3" json:"epoch_nonce,omitempty"`
	SlotsPerKesPeriod                               uint64                           `protobuf:"varint,12,opt,name=slots_per_kes_period,json=slotsPerKesPeriod,proto3" json:"slots_per_kes_period,omitempty"`
	CurrentEpochStartSlot                           uint64                           `protobuf:"varint,13,opt,name=current_epoch_start_slot,json=currentEpochStartSlot,proto3" json:"current_epoch_start_slot,omitempty"`
	CurrentEpochEndSlotExclusive                    uint64                           `protobuf:"varint,14,opt,name=current_epoch_end_slot_exclusive,json=currentEpochEndSlotExclusive,proto3" json:"current_epoch_end_slot_exclusive,omitempty"`
	SystemStartUnixNs                               uint64                           `protobuf:"varint,15,opt,name=system_start_unix_ns,json=systemStartUnixNs,proto3" json:"system_start_unix_ns,omitempty"`
	SlotLengthNs                                    uint64                           `protobuf:"varint,16,opt,name=slot_length_ns,json=slotLengthNs,proto3" json:"slot_length_ns,omitempty"`
	EpochContexts                                   []*EpochContext                  `protobuf:"bytes,17,rep,name=epoch_contexts,json=epochContexts,proto3" json:"epoch_contexts,omitempty"`
	LatestCheckpointHeight                          *Height                          `protobuf:"bytes,19,opt,name=latest_checkpoint_height,json=latestCheckpointHeight,proto3" json:"latest_checkpoint_height,omitempty"`
	LatestCheckpointBlockHash                       string                           `protobuf:"bytes,20,opt,name=latest_checkpoint_block_hash,json=latestCheckpointBlockHash,proto3" json:"latest_checkpoint_block_hash,omitempty"`
	LatestCheckpointEpoch                           uint64                           `protobuf:"varint,21,opt,name=latest_checkpoint_epoch,json=latestCheckpointEpoch,proto3" json:"latest_checkpoint_epoch,omitempty"`
	MaxKesEvolutions                                uint64                           `protobuf:"varint,22,opt,name=max_kes_evolutions,json=maxKesEvolutions,proto3" json:"max_kes_evolutions,omitempty"`
	LatestCheckpointOperationalCertificateCounters  []*OperationalCertificateCounter `protobuf:"bytes,23,rep,name=latest_checkpoint_operational_certificate_counters,json=latestCheckpointOperationalCertificateCounters,proto3" json:"latest_checkpoint_operational_certificate_counters,omitempty"`
	OperationalCertificateCounterHistoryStartHeight *Height                          `protobuf:"bytes,24,opt,name=operational_certificate_counter_history_start_height,json=operationalCertificateCounterHistoryStartHeight,proto3" json:"operational_certificate_counter_history_start_height,omitempty"`
	ActiveSlotCoefficientNumerator                  uint64                           `protobuf:"varint,25,opt,name=active_slot_coefficient_numerator,json=activeSlotCoefficientNumerator,proto3" json:"active_slot_coefficient_numerator,omitempty"`
	ActiveSlotCoefficientDenominator                uint64                           `protobuf:"varint,26,opt,name=active_slot_coefficient_denominator,json=activeSlotCoefficientDenominator,proto3" json:"active_slot_coefficient_denominator,omitempty"`
	MaxClockDrift                                   time.Duration                    `protobuf:"bytes,27,opt,name=max_clock_drift,json=maxClockDrift,proto3,stdduration" json:"max_clock_drift"`
	LatestCheckpointSlot                            uint64                           `protobuf:"varint,28,opt,name=latest_checkpoint_slot,json=latestCheckpointSlot,proto3" json:"latest_checkpoint_slot,omitempty"`
	LatestCheckpointTimestamp                       uint64                           `protobuf:"varint,29,opt,name=latest_checkpoint_timestamp,json=latestCheckpointTimestamp,proto3" json:"latest_checkpoint_timestamp,omitempty"`
	PacketLanePolicyId                              []byte                           `protobuf:"bytes,30,opt,name=packet_lane_policy_id,json=packetLanePolicyId,proto3" json:"packet_lane_policy_id,omitempty"`
	EpochContextChallenges                          []*EpochContextChallenge         `protobuf:"bytes,31,rep,name=epoch_context_challenges,json=epochContextChallenges,proto3" json:"epoch_context_challenges,omitempty"`
	LatestCheckpointNonceState                      *PraosNonceState                 `protobuf:"bytes,32,opt,name=latest_checkpoint_nonce_state,json=latestCheckpointNonceState,proto3" json:"latest_checkpoint_nonce_state,omitempty"`
	RandomnessStabilisationWindowSlots              uint64                           `protobuf:"varint,33,opt,name=randomness_stabilisation_window_slots,json=randomnessStabilisationWindowSlots,proto3" json:"randomness_stabilisation_window_slots,omitempty"`
	LatestCheckpointPoolRegistry                    *PoolRegistryState               `protobuf:"bytes,34,opt,name=latest_checkpoint_pool_registry,json=latestCheckpointPoolRegistry,proto3" json:"latest_checkpoint_pool_registry,omitempty"`
}

type PoolRegistrationBinding struct {
	PoolId                string `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	VrfKeyHash            []byte `protobuf:"bytes,2,opt,name=vrf_key_hash,json=vrfKeyHash,proto3" json:"vrf_key_hash,omitempty"`
	FirstRegistrationSlot uint64 `protobuf:"varint,3,opt,name=first_registration_slot,json=firstRegistrationSlot,proto3" json:"first_registration_slot,omitempty"`
}

type PoolRegistrationRecord struct {
	Registration          *PoolRegistrationBinding `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	Registered            bool                     `protobuf:"varint,2,opt,name=registered,proto3" json:"registered,omitempty"`
	PendingVrfKeyHash     []byte                   `protobuf:"bytes,3,opt,name=pending_vrf_key_hash,json=pendingVrfKeyHash,proto3" json:"pending_vrf_key_hash,omitempty"`
	PendingEffectiveEpoch uint64                   `protobuf:"varint,4,opt,name=pending_effective_epoch,json=pendingEffectiveEpoch,proto3" json:"pending_effective_epoch,omitempty"`
	RetirementEpoch       uint64                   `protobuf:"varint,5,opt,name=retirement_epoch,json=retirementEpoch,proto3" json:"retirement_epoch,omitempty"`
}

type PoolRegistryState struct {
	Epoch     uint64                     `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Pools     []*PoolRegistrationRecord  `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	Mark      []*PoolRegistrationBinding `protobuf:"bytes,3,rep,name=mark,proto3" json:"mark,omitempty"`
	Effective []*PoolRegistrationBinding `protobuf:"bytes,4,rep,name=effective,proto3" json:"effective,omitempty"`
}

type PraosNonceState struct {
	EpochNonce            []byte `protobuf:"bytes,1,opt,name=epoch_nonce,json=epochNonce,proto3" json:"epoch_nonce,omitempty"`
	EvolvingNonce         []byte `protobuf:"bytes,2,opt,name=evolving_nonce,json=evolvingNonce,proto3" json:"evolving_nonce,omitempty"`
	CandidateNonce        []byte `protobuf:"bytes,3,opt,name=candidate_nonce,json=candidateNonce,proto3" json:"candidate_nonce,omitempty"`
	LastAppliedBlockNonce []byte `protobuf:"bytes,4,opt,name=last_applied_block_nonce,json=lastAppliedBlockNonce,proto3" json:"last_applied_block_nonce,omitempty"`
	LastEpochBlockNonce   []byte `protobuf:"bytes,5,opt,name=last_epoch_block_nonce,json=lastEpochBlockNonce,proto3" json:"last_epoch_block_nonce,omitempty"`
}

type EpochContextChallenge struct {
	Epoch             uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	UsableAfterUnixNs uint64 `protobuf:"varint,2,opt,name=usable_after_unix_ns,json=usableAfterUnixNs,proto3" json:"usable_after_unix_ns,omitempty"`
}

type ConsensusState struct {
	Timestamp           uint64             `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IbcStateRoot        []byte             `protobuf:"bytes,2,opt,name=ibc_state_root,json=ibcStateRoot,proto3" json:"ibc_state_root,omitempty"`
	AcceptedBlockHash   string             `protobuf:"bytes,3,opt,name=accepted_block_hash,json=acceptedBlockHash,proto3" json:"accepted_block_hash,omitempty"`
	AcceptedEpoch       uint64             `protobuf:"varint,4,opt,name=accepted_epoch,json=acceptedEpoch,proto3" json:"accepted_epoch,omitempty"`
	UniquePoolsCount    uint64             `protobuf:"varint,5,opt,name=unique_pools_count,json=uniquePoolsCount,proto3" json:"unique_pools_count,omitempty"`
	UniqueStakeBps      uint64             `protobuf:"varint,6,opt,name=unique_stake_bps,json=uniqueStakeBps,proto3" json:"unique_stake_bps,omitempty"`
	SecurityScoreBps    uint64             `protobuf:"varint,7,opt,name=security_score_bps,json=securityScoreBps,proto3" json:"security_score_bps,omitempty"`
	PacketStateSnapshot []byte             `protobuf:"bytes,8,opt,name=packet_state_snapshot,json=packetStateSnapshot,proto3" json:"packet_state_snapshot,omitempty"`
	NonceState          *PraosNonceState   `protobuf:"bytes,9,opt,name=nonce_state,json=nonceState,proto3" json:"nonce_state,omitempty"`
	PoolRegistry        *PoolRegistryState `protobuf:"bytes,10,opt,name=pool_registry,json=poolRegistry,proto3" json:"pool_registry,omitempty"`
}

type Misbehaviour struct {
	ClientId             string               `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProbabilisticHeader1 *ProbabilisticHeader `protobuf:"bytes,2,opt,name=probabilistic_header_1,json=probabilisticHeader1,proto3" json:"probabilistic_header_1,omitempty"`
	ProbabilisticHeader2 *ProbabilisticHeader `protobuf:"bytes,3,opt,name=probabilistic_header_2,json=probabilisticHeader2,proto3" json:"probabilistic_header_2,omitempty"`
}

type ProbabilisticBlock struct {
	Height     *Height `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Slot       uint64  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Hash       string  `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Epoch      uint64  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Timestamp  uint64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockCbor  []byte  `protobuf:"bytes,9,opt,name=block_cbor,json=blockCbor,proto3" json:"block_cbor,omitempty"`
	HeaderCbor []byte  `protobuf:"bytes,10,opt,name=header_cbor,json=headerCbor,proto3" json:"header_cbor,omitempty"`
}

type ProbabilisticHeader struct {
	TrustedHeight          *Height               `protobuf:"bytes,1,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height,omitempty"`
	AnchorBlock            *ProbabilisticBlock   `protobuf:"bytes,2,opt,name=anchor_block,json=anchorBlock,proto3" json:"anchor_block,omitempty"`
	DescendantBlocks       []*ProbabilisticBlock `protobuf:"bytes,3,rep,name=descendant_blocks,json=descendantBlocks,proto3" json:"descendant_blocks,omitempty"`
	HostStateTxHash        string                `protobuf:"bytes,4,opt,name=host_state_tx_hash,json=hostStateTxHash,proto3" json:"host_state_tx_hash,omitempty"`
	HostStateTxOutputIndex uint32                `protobuf:"varint,6,opt,name=host_state_tx_output_index,json=hostStateTxOutputIndex,proto3" json:"host_state_tx_output_index,omitempty"`
	BridgeBlocks           []*ProbabilisticBlock `protobuf:"bytes,10,rep,name=bridge_blocks,json=bridgeBlocks,proto3" json:"bridge_blocks,omitempty"`
	NewEpochContext        *EpochContext         `protobuf:"bytes,11,opt,name=new_epoch_context,json=newEpochContext,proto3" json:"new_epoch_context,omitempty"`
	IsCheckpoint           bool                  `protobuf:"varint,12,opt,name=is_checkpoint,json=isCheckpoint,proto3" json:"is_checkpoint,omitempty"`
}
