// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/probabilistic/v1/probabilistic.proto

package probabilistic

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Height struct {
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	RevisionHeight uint64 `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
}

func (m *Height) Reset()         { *m = Height{} }
func (m *Height) String() string { return proto.CompactTextString(m) }
func (*Height) ProtoMessage()    {}
func (*Height) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{0}
}
func (m *Height) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Height) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Height.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Height) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Height.Merge(m, src)
}
func (m *Height) XXX_Size() int {
	return m.Size()
}
func (m *Height) XXX_DiscardUnknown() {
	xxx_messageInfo_Height.DiscardUnknown(m)
}

var xxx_messageInfo_Height proto.InternalMessageInfo

type StakeDistributionEntry struct {
	PoolId                string `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Stake                 uint64 `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	VrfKeyHash            []byte `protobuf:"bytes,3,opt,name=vrf_key_hash,json=vrfKeyHash,proto3" json:"vrf_key_hash,omitempty"`
	FirstRegistrationSlot uint64 `protobuf:"varint,4,opt,name=first_registration_slot,json=firstRegistrationSlot,proto3" json:"first_registration_slot,omitempty"`
}

func (m *StakeDistributionEntry) Reset()         { *m = StakeDistributionEntry{} }
func (m *StakeDistributionEntry) String() string { return proto.CompactTextString(m) }
func (*StakeDistributionEntry) ProtoMessage()    {}
func (*StakeDistributionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{1}
}
func (m *StakeDistributionEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakeDistributionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakeDistributionEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakeDistributionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeDistributionEntry.Merge(m, src)
}
func (m *StakeDistributionEntry) XXX_Size() int {
	return m.Size()
}
func (m *StakeDistributionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeDistributionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StakeDistributionEntry proto.InternalMessageInfo

type EpochContext struct {
	Epoch                 uint64                    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	StakeDistribution     []*StakeDistributionEntry `protobuf:"bytes,2,rep,name=stake_distribution,json=stakeDistribution,proto3" json:"stake_distribution,omitempty"`
	EpochNonce            []byte                    `protobuf:"bytes,3,opt,name=epoch_nonce,json=epochNonce,proto3" json:"epoch_nonce,omitempty"`
	SlotsPerKesPeriod     uint64                    `protobuf:"varint,4,opt,name=slots_per_kes_period,json=slotsPerKesPeriod,proto3" json:"slots_per_kes_period,omitempty"`
	EpochStartSlot        uint64                    `protobuf:"varint,5,opt,name=epoch_start_slot,json=epochStartSlot,proto3" json:"epoch_start_slot,omitempty"`
	EpochEndSlotExclusive uint64                    `protobuf:"varint,6,opt,name=epoch_end_slot_exclusive,json=epochEndSlotExclusive,proto3" json:"epoch_end_slot_exclusive,omitempty"`
}

func (m *EpochContext) Reset()         { *m = EpochContext{} }
func (m *EpochContext) String() string { return proto.CompactTextString(m) }
func (*EpochContext) ProtoMessage()    {}
func (*EpochContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{2}
}
func (m *EpochContext) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochContext.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochContext.Merge(m, src)
}
func (m *EpochContext) XXX_Size() int {
	return m.Size()
}
func (m *EpochContext) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochContext.DiscardUnknown(m)
}

var xxx_messageInfo_EpochContext proto.InternalMessageInfo

type ClientState struct {
	ChainId                      string                    `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	LatestHeight                 *Height                   `protobuf:"bytes,2,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	FrozenHeight                 *Height                   `protobuf:"bytes,3,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	CurrentEpoch                 uint64                    `protobuf:"varint,4,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	TrustingPeriod               time.Duration             `protobuf:"bytes,5,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	UpgradePath                  []string                  `protobuf:"bytes,7,rep,name=upgrade_path,json=upgradePath,proto3" json:"upgrade_path,omitempty"`
	HostStateNftPolicyId         []byte                    `protobuf:"bytes,8,opt,name=host_state_nft_policy_id,json=hostStateNftPolicyId,proto3" json:"host_state_nft_policy_id,omitempty"`
	HostStateNftTokenName        []byte                    `protobuf:"bytes,9,opt,name=host_state_nft_token_name,json=hostStateNftTokenName,proto3" json:"host_state_nft_token_name,omitempty"`
	EpochStakeDistribution       []*StakeDistributionEntry `protobuf:"bytes,10,rep,name=epoch_stake_distribution,json=epochStakeDistribution,proto3" json:"epoch_stake_distribution,omitempty"`
	EpochNonce                   []byte                    `protobuf:"bytes,11,opt,name=epoch_nonce,json=epochNonce,proto3" json:"epoch_nonce,omitempty"`
	SlotsPerKesPeriod            uint64                    `protobuf:"varint,12,opt,name=slots_per_kes_period,json=slotsPerKesPeriod,proto3" json:"slots_per_kes_period,omitempty"`
	CurrentEpochStartSlot        uint64                    `protobuf:"varint,13,opt,name=current_epoch_start_slot,json=currentEpochStartSlot,proto3" json:"current_epoch_start_slot,omitempty"`
	CurrentEpochEndSlotExclusive uint64                    `protobuf:"varint,14,opt,name=current_epoch_end_slot_exclusive,json=currentEpochEndSlotExclusive,proto3" json:"current_epoch_end_slot_exclusive,omitempty"`
	SystemStartUnixNs            uint64                    `protobuf:"varint,15,opt,name=system_start_unix_ns,json=systemStartUnixNs,proto3" json:"system_start_unix_ns,omitempty"`
	SlotLengthNs                 uint64                    `protobuf:"varint,16,opt,name=slot_length_ns,json=slotLengthNs,proto3" json:"slot_length_ns,omitempty"`
	EpochContexts                []*EpochContext           `protobuf:"bytes,17,rep,name=epoch_contexts,json=epochContexts,proto3" json:"epoch_contexts,omitempty"`
	// The latest authenticated Cardano block, which may be newer than
	// latest_height when rootless checkpoint updates are used for catch-up.
	LatestCheckpointHeight    *Height `protobuf:"bytes,19,opt,name=latest_checkpoint_height,json=latestCheckpointHeight,proto3" json:"latest_checkpoint_height,omitempty"`
	LatestCheckpointBlockHash string  `protobuf:"bytes,20,opt,name=latest_checkpoint_block_hash,json=latestCheckpointBlockHash,proto3" json:"latest_checkpoint_block_hash,omitempty"`
	LatestCheckpointEpoch     uint64  `protobuf:"varint,21,opt,name=latest_checkpoint_epoch,json=latestCheckpointEpoch,proto3" json:"latest_checkpoint_epoch,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{3}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type ConsensusState struct {
	Timestamp         uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IbcStateRoot      []byte `protobuf:"bytes,2,opt,name=ibc_state_root,json=ibcStateRoot,proto3" json:"ibc_state_root,omitempty"`
	AcceptedBlockHash string `protobuf:"bytes,3,opt,name=accepted_block_hash,json=acceptedBlockHash,proto3" json:"accepted_block_hash,omitempty"`
	AcceptedEpoch     uint64 `protobuf:"varint,4,opt,name=accepted_epoch,json=acceptedEpoch,proto3" json:"accepted_epoch,omitempty"`
	UniquePoolsCount  uint64 `protobuf:"varint,5,opt,name=unique_pools_count,json=uniquePoolsCount,proto3" json:"unique_pools_count,omitempty"`
	UniqueStakeBps    uint64 `protobuf:"varint,6,opt,name=unique_stake_bps,json=uniqueStakeBps,proto3" json:"unique_stake_bps,omitempty"`
	SecurityScoreBps  uint64 `protobuf:"varint,7,opt,name=security_score_bps,json=securityScoreBps,proto3" json:"security_score_bps,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{4}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

type Misbehaviour struct {
	ClientId             string               `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Deprecated: Do not use.
	ProbabilisticHeader1 *ProbabilisticHeader `protobuf:"bytes,2,opt,name=probabilistic_header_1,json=probabilisticHeader1,proto3" json:"probabilistic_header_1,omitempty"`
	ProbabilisticHeader2 *ProbabilisticHeader `protobuf:"bytes,3,opt,name=probabilistic_header_2,json=probabilisticHeader2,proto3" json:"probabilistic_header_2,omitempty"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{5}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return m.Size()
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

type ProbabilisticBlock struct {
	Height    *Height `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Slot      uint64  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Hash      string  `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Epoch     uint64  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Timestamp uint64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockCbor []byte  `protobuf:"bytes,9,opt,name=block_cbor,json=blockCbor,proto3" json:"block_cbor,omitempty"`
}

func (m *ProbabilisticBlock) Reset()         { *m = ProbabilisticBlock{} }
func (m *ProbabilisticBlock) String() string { return proto.CompactTextString(m) }
func (*ProbabilisticBlock) ProtoMessage()    {}
func (*ProbabilisticBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{6}
}
func (m *ProbabilisticBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProbabilisticBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProbabilisticBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProbabilisticBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbabilisticBlock.Merge(m, src)
}
func (m *ProbabilisticBlock) XXX_Size() int {
	return m.Size()
}
func (m *ProbabilisticBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbabilisticBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ProbabilisticBlock proto.InternalMessageInfo

type ProbabilisticHeader struct {
	TrustedHeight          *Height               `protobuf:"bytes,1,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height,omitempty"`
	AnchorBlock            *ProbabilisticBlock   `protobuf:"bytes,2,opt,name=anchor_block,json=anchorBlock,proto3" json:"anchor_block,omitempty"`
	DescendantBlocks       []*ProbabilisticBlock `protobuf:"bytes,3,rep,name=descendant_blocks,json=descendantBlocks,proto3" json:"descendant_blocks,omitempty"`
	HostStateTxHash        string                `protobuf:"bytes,4,opt,name=host_state_tx_hash,json=hostStateTxHash,proto3" json:"host_state_tx_hash,omitempty"`
	HostStateTxOutputIndex uint32                `protobuf:"varint,6,opt,name=host_state_tx_output_index,json=hostStateTxOutputIndex,proto3" json:"host_state_tx_output_index,omitempty"`
	BridgeBlocks           []*ProbabilisticBlock `protobuf:"bytes,10,rep,name=bridge_blocks,json=bridgeBlocks,proto3" json:"bridge_blocks,omitempty"`
	NewEpochContext        *EpochContext         `protobuf:"bytes,11,opt,name=new_epoch_context,json=newEpochContext,proto3" json:"new_epoch_context,omitempty"`
	// Checkpoints authenticate Cardano chain progression without creating an
	// IBC consensus state or renewing the trusting period.
	IsCheckpoint bool `protobuf:"varint,12,opt,name=is_checkpoint,json=isCheckpoint,proto3" json:"is_checkpoint,omitempty"`
}

func (m *ProbabilisticHeader) Reset()         { *m = ProbabilisticHeader{} }
func (m *ProbabilisticHeader) String() string { return proto.CompactTextString(m) }
func (*ProbabilisticHeader) ProtoMessage()    {}
func (*ProbabilisticHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dbfbf493c1ef770, []int{7}
}
func (m *ProbabilisticHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProbabilisticHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProbabilisticHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProbabilisticHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbabilisticHeader.Merge(m, src)
}
func (m *ProbabilisticHeader) XXX_Size() int {
	return m.Size()
}
func (m *ProbabilisticHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbabilisticHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ProbabilisticHeader proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Height)(nil), "ibc.lightclients.probabilistic.v1.Height")
	proto.RegisterType((*StakeDistributionEntry)(nil), "ibc.lightclients.probabilistic.v1.StakeDistributionEntry")
	proto.RegisterType((*EpochContext)(nil), "ibc.lightclients.probabilistic.v1.EpochContext")
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.probabilistic.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.probabilistic.v1.ConsensusState")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.probabilistic.v1.Misbehaviour")
	proto.RegisterType((*ProbabilisticBlock)(nil), "ibc.lightclients.probabilistic.v1.ProbabilisticBlock")
	proto.RegisterType((*ProbabilisticHeader)(nil), "ibc.lightclients.probabilistic.v1.ProbabilisticHeader")
}

func init() {
	proto.RegisterFile("ibc/lightclients/probabilistic/v1/probabilistic.proto", fileDescriptor_4dbfbf493c1ef770)
}

var fileDescriptor_4dbfbf493c1ef770 = []byte{
	// 1435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x72, 0x1b, 0xc5,
	0x16, 0xb6, 0x6c, 0x59, 0x96, 0xda, 0x92, 0x2d, 0x77, 0x1c, 0x67, 0x9c, 0xca, 0xb5, 0x1d, 0xe7,
	0xde, 0xba, 0xa6, 0xc0, 0x52, 0xd9, 0x54, 0x7e, 0x08, 0x0b, 0x0a, 0x3b, 0xa6, 0xe2, 0x24, 0x08,
	0xd7, 0x38, 0x50, 0x54, 0x58, 0x0c, 0x33, 0x3d, 0x2d, 0x4d, 0x97, 0xa5, 0xee, 0xa1, 0xbb, 0x47,
	0x91, 0x79, 0x00, 0x2a, 0x4b, 0x96, 0x2c, 0xd9, 0xf1, 0x08, 0x3c, 0x00, 0x0b, 0xc2, 0x2e, 0x4b,
	0x56, 0x81, 0x72, 0x76, 0x3c, 0x04, 0x45, 0xf5, 0xcf, 0x48, 0x33, 0x8e, 0x02, 0x76, 0xc2, 0xc6,
	0xd6, 0x9c, 0xbf, 0xee, 0x73, 0xce, 0xf7, 0x9d, 0xd3, 0xe0, 0x3a, 0x09, 0x50, 0xb3, 0x4b, 0x3a,
	0x91, 0x44, 0x5d, 0x82, 0xa9, 0x14, 0xcd, 0x98, 0xb3, 0xc0, 0x0f, 0x48, 0x97, 0x08, 0x49, 0x50,
	0xb3, 0xbf, 0x95, 0x17, 0x34, 0x62, 0xce, 0x24, 0x83, 0x57, 0x49, 0x80, 0x1a, 0x59, 0xb7, 0x46,
	0xde, 0xaa, 0xbf, 0x75, 0x79, 0xb1, 0xc3, 0x3a, 0x4c, 0x5b, 0x37, 0xd5, 0x2f, 0xe3, 0x78, 0x79,
	0xa5, 0xc3, 0x58, 0xa7, 0x8b, 0x9b, 0xfa, 0x2b, 0x48, 0xda, 0xcd, 0x30, 0xe1, 0xbe, 0x24, 0x8c,
	0x1a, 0xfd, 0xfa, 0x97, 0xa0, 0x74, 0x17, 0xab, 0xb8, 0xf0, 0xff, 0x60, 0x9e, 0xe3, 0x3e, 0x11,
	0x84, 0x51, 0x8f, 0x26, 0xbd, 0x00, 0x73, 0xa7, 0xb0, 0x56, 0xd8, 0x28, 0xba, 0x73, 0xa9, 0xb8,
	0xa5, 0xa5, 0x39, 0xc3, 0x48, 0xfb, 0x3a, 0x93, 0x79, 0x43, 0x13, 0xf1, 0x76, 0xf1, 0xc9, 0xf7,
	0xab, 0x13, 0xeb, 0x3f, 0x14, 0xc0, 0xd2, 0xa1, 0xf4, 0x8f, 0xf0, 0x1d, 0x22, 0x24, 0x27, 0x41,
	0xa2, 0x4e, 0xdf, 0xa3, 0x92, 0x1f, 0xc3, 0x4b, 0x60, 0x26, 0x66, 0xac, 0xeb, 0x91, 0x50, 0x1f,
	0x55, 0x71, 0x4b, 0xea, 0x73, 0x3f, 0x84, 0x8b, 0x60, 0x5a, 0x28, 0x17, 0x1b, 0xd8, 0x7c, 0xc0,
	0x35, 0x50, 0xed, 0xf3, 0xb6, 0x77, 0x84, 0x8f, 0xbd, 0xc8, 0x17, 0x91, 0x33, 0xb5, 0x56, 0xd8,
	0xa8, 0xba, 0xa0, 0xcf, 0xdb, 0xf7, 0xf1, 0xf1, 0x5d, 0x5f, 0x44, 0xf0, 0x06, 0xb8, 0xd4, 0x26,
	0x5c, 0x48, 0x8f, 0xe3, 0x8e, 0x3a, 0x4d, 0x67, 0xea, 0x89, 0x2e, 0x93, 0x4e, 0x51, 0x47, 0xba,
	0xa8, 0xd5, 0x6e, 0x46, 0x7b, 0xd8, 0x65, 0xe9, 0x4d, 0x7f, 0x99, 0x04, 0xd5, 0xbd, 0x98, 0xa1,
	0x68, 0x97, 0x51, 0x89, 0x07, 0x52, 0x5d, 0x03, 0xab, 0x6f, 0x5b, 0x08, 0xf3, 0x01, 0x23, 0x00,
	0xf5, 0x7d, 0xbc, 0x30, 0x93, 0x90, 0x33, 0xb9, 0x36, 0xb5, 0x31, 0xbb, 0xfd, 0x5e, 0xe3, 0x1f,
	0x1b, 0xd5, 0x18, 0x5f, 0x0c, 0x77, 0x41, 0x9c, 0x96, 0xc3, 0x55, 0x30, 0xab, 0x8f, 0xf4, 0x28,
	0xa3, 0x08, 0xa7, 0xf9, 0x6a, 0x51, 0x4b, 0x49, 0x60, 0x13, 0x2c, 0xaa, 0xe4, 0x84, 0x17, 0x63,
	0xee, 0x1d, 0x61, 0xfd, 0x9f, 0xb0, 0xd0, 0x26, 0xbb, 0xa0, 0x75, 0x07, 0x98, 0xdf, 0xc7, 0xea,
	0x2f, 0x61, 0x21, 0xdc, 0x00, 0x75, 0x13, 0x51, 0x48, 0x9f, 0x4b, 0x53, 0x99, 0x69, 0xd3, 0x3c,
	0x2d, 0x3f, 0x54, 0x62, 0x55, 0x12, 0x78, 0x13, 0x38, 0xc6, 0x12, 0xd3, 0x50, 0xdb, 0x79, 0x78,
	0x80, 0xba, 0x89, 0x20, 0x7d, 0xec, 0x94, 0x4c, 0x2d, 0xb5, 0x7e, 0x8f, 0x86, 0xca, 0x7e, 0x2f,
	0x55, 0xda, 0x5a, 0xfe, 0x54, 0x01, 0xb3, 0xbb, 0xba, 0x02, 0x87, 0xd2, 0x97, 0x18, 0x2e, 0x83,
	0x32, 0x8a, 0x7c, 0x42, 0x47, 0xbd, 0x9e, 0xd1, 0xdf, 0xfb, 0x21, 0x6c, 0x81, 0x5a, 0xd7, 0x97,
	0x58, 0xc8, 0x2c, 0x9a, 0x66, 0xb7, 0xdf, 0x3a, 0x43, 0x29, 0x0d, 0xd0, 0xdc, 0xaa, 0xf1, 0xb7,
	0x40, 0x6e, 0x81, 0x5a, 0x9b, 0xb3, 0xaf, 0xf1, 0x10, 0x9d, 0x53, 0xe7, 0x8e, 0x67, 0xfc, 0x6d,
	0xbc, 0x6b, 0xa0, 0x86, 0x12, 0xce, 0x31, 0x95, 0x9e, 0x41, 0x83, 0xa9, 0x6e, 0xd5, 0x0a, 0x35,
	0x62, 0xe0, 0x03, 0x30, 0x2f, 0x79, 0x22, 0x24, 0xa1, 0x9d, 0xb4, 0x09, 0xd3, 0xfa, 0xd8, 0xe5,
	0x86, 0x61, 0x60, 0x23, 0x65, 0x60, 0xe3, 0x8e, 0x65, 0xe0, 0x4e, 0xf9, 0xe9, 0xf3, 0xd5, 0x89,
	0xef, 0x7e, 0x5b, 0x2d, 0xb8, 0x73, 0xa9, 0xaf, 0x6d, 0xd3, 0x55, 0x50, 0x4d, 0xe2, 0x0e, 0xf7,
	0x43, 0xec, 0xc5, 0xbe, 0x8c, 0x9c, 0x99, 0xb5, 0xa9, 0x8d, 0x8a, 0x3b, 0x6b, 0x65, 0x07, 0xbe,
	0x54, 0x50, 0x77, 0x22, 0x26, 0xa4, 0x6a, 0xa4, 0xc4, 0x1e, 0x6d, 0x4b, 0x2f, 0x66, 0x5d, 0x82,
	0x8e, 0x55, 0x81, 0xcb, 0x1a, 0x28, 0x8b, 0x4a, 0xaf, 0xab, 0xdf, 0x6a, 0xcb, 0x03, 0xad, 0xdc,
	0x0f, 0xe1, 0x2d, 0xb0, 0x7c, 0xca, 0x4f, 0xb2, 0x23, 0x4c, 0x3d, 0xea, 0xf7, 0xb0, 0x53, 0xd1,
	0x8e, 0x17, 0xb3, 0x8e, 0x0f, 0x95, 0xb6, 0xe5, 0xf7, 0x30, 0x14, 0x29, 0x22, 0xc6, 0xa0, 0x1f,
	0xbc, 0x29, 0xfa, 0x97, 0x52, 0xf8, 0xfd, 0x3d, 0x05, 0x66, 0xcf, 0x4c, 0x81, 0xea, 0xab, 0x28,
	0x70, 0x13, 0x38, 0xb9, 0x76, 0x66, 0xa9, 0x50, 0x33, 0xc0, 0xce, 0x76, 0x76, 0xc4, 0x88, 0x8f,
	0xc0, 0x5a, 0xde, 0x71, 0x0c, 0x33, 0xe6, 0x74, 0x80, 0x2b, 0xd9, 0x00, 0xa7, 0x09, 0xa2, 0x6f,
	0x7c, 0x2c, 0x24, 0xee, 0xd9, 0x93, 0x13, 0x4a, 0x06, 0x1e, 0x15, 0xce, 0xbc, 0xbd, 0xb1, 0xd6,
	0xe9, 0x63, 0x3f, 0xa5, 0x64, 0xd0, 0x12, 0xf0, 0xbf, 0x60, 0x4e, 0x1f, 0xd3, 0xc5, 0xb4, 0x23,
	0x23, 0x65, 0x5a, 0x37, 0x08, 0x54, 0xd2, 0x07, 0x5a, 0xd8, 0x12, 0xf0, 0x33, 0x60, 0x28, 0xec,
	0x21, 0x33, 0xbd, 0x84, 0xb3, 0xa0, 0x9b, 0xd2, 0x3c, 0x43, 0x53, 0xb2, 0x53, 0xcf, 0xad, 0xe1,
	0xcc, 0x97, 0x80, 0x08, 0x38, 0x96, 0x9e, 0x28, 0xc2, 0xe8, 0x28, 0x66, 0x84, 0x0e, 0x99, 0x7a,
	0xe1, 0xbc, 0xcc, 0x5a, 0x32, 0xa1, 0x76, 0x87, 0x91, 0x2c, 0xc7, 0x3e, 0x00, 0x57, 0x5e, 0x3e,
	0x24, 0xe8, 0x32, 0x74, 0x64, 0x46, 0xfd, 0xa2, 0x1e, 0x19, 0xcb, 0xa7, 0xbd, 0x77, 0x94, 0x45,
	0x3a, 0xf9, 0x5f, 0x0e, 0x60, 0xe8, 0x7a, 0xd1, 0x34, 0xf5, 0xb4, 0xaf, 0xce, 0xd9, 0x4c, 0xab,
	0x7b, 0xc5, 0x72, 0xa9, 0x3e, 0xe3, 0xd6, 0x23, 0x9c, 0x70, 0x7d, 0x63, 0x2f, 0xf6, 0xb9, 0xdf,
	0x13, 0xeb, 0x3f, 0x4e, 0x82, 0xb9, 0x5d, 0x46, 0x05, 0xa6, 0x22, 0x11, 0x66, 0x90, 0x5d, 0x01,
	0x15, 0x49, 0x7a, 0x58, 0x48, 0xbf, 0x17, 0xdb, 0xbd, 0x30, 0x12, 0xa8, 0x56, 0x91, 0x00, 0x59,
	0x72, 0x71, 0xc6, 0xcc, 0x30, 0xab, 0xba, 0x55, 0x12, 0x20, 0xed, 0xef, 0x32, 0x26, 0x61, 0x03,
	0x5c, 0xf0, 0x11, 0xc2, 0xb1, 0xc4, 0x61, 0x36, 0xc9, 0x29, 0x9d, 0xe4, 0x42, 0xaa, 0x1a, 0x25,
	0xf7, 0x3f, 0x30, 0x37, 0xb4, 0xcf, 0x8e, 0xa0, 0x5a, 0x2a, 0x35, 0x33, 0xe8, 0x1d, 0x00, 0x13,
	0x4a, 0xbe, 0x4a, 0xb0, 0xa7, 0xd6, 0xa8, 0xf0, 0x10, 0x4b, 0x68, 0x3a, 0xde, 0xeb, 0x46, 0x73,
	0xa0, 0x14, 0xbb, 0x4a, 0xae, 0x56, 0x81, 0xb5, 0x36, 0x7c, 0x0e, 0x62, 0x61, 0x07, 0xfb, 0x9c,
	0x91, 0x6b, 0x32, 0xee, 0xc4, 0x42, 0xc5, 0x15, 0x18, 0x25, 0x9c, 0xc8, 0x63, 0x4f, 0x20, 0xc6,
	0x8d, 0xed, 0x8c, 0x89, 0x9b, 0x6a, 0x0e, 0x95, 0x62, 0x27, 0x16, 0x76, 0xfe, 0xff, 0x3c, 0x09,
	0xaa, 0x1f, 0x13, 0x11, 0xe0, 0xc8, 0xef, 0x13, 0x96, 0x70, 0xb8, 0x0a, 0x2a, 0x06, 0x1c, 0xc3,
	0x0d, 0xb0, 0x33, 0xe9, 0x14, 0xdc, 0xb2, 0x11, 0xee, 0x87, 0xf0, 0x9b, 0x02, 0x58, 0xca, 0xc1,
	0xc6, 0x8b, 0xb0, 0x1f, 0x62, 0xee, 0x6d, 0xd9, 0x85, 0x70, 0xe3, 0x0c, 0x30, 0x3b, 0xc8, 0x0a,
	0xee, 0x6a, 0xff, 0x1d, 0xe7, 0xe4, 0xf9, 0xea, 0xe2, 0x18, 0xc5, 0x96, 0xbb, 0x18, 0x8f, 0x91,
	0xbe, 0xfa, 0x22, 0xdb, 0x76, 0x93, 0xfc, 0xdb, 0x17, 0xd9, 0x1e, 0x7b, 0x91, 0x6d, 0x5b, 0xc9,
	0x3f, 0x0a, 0x00, 0xe6, 0x9c, 0x34, 0x2e, 0xe0, 0x87, 0xa0, 0x64, 0x49, 0x58, 0x38, 0x2f, 0x09,
	0xad, 0x23, 0x84, 0xa0, 0xa8, 0xa7, 0x9e, 0x79, 0x64, 0xe9, 0xdf, 0x4a, 0x96, 0xc1, 0xa2, 0xfe,
	0x3d, 0x7a, 0x06, 0x4d, 0x67, 0x9f, 0x41, 0x39, 0x22, 0x94, 0x4e, 0x13, 0xe1, 0x3f, 0x00, 0x18,
	0x64, 0xa3, 0x80, 0x71, 0xbb, 0x57, 0x2a, 0x5a, 0xb2, 0x1b, 0x30, 0x3e, 0xa4, 0x5d, 0xb1, 0x3e,
	0x7d, 0xaf, 0x58, 0x9e, 0xa9, 0x97, 0xef, 0x15, 0xcb, 0xe5, 0x7a, 0x65, 0xfd, 0xcf, 0x22, 0xb8,
	0x30, 0xa6, 0x42, 0xf0, 0x00, 0x98, 0x15, 0x89, 0x43, 0xef, 0x75, 0xb3, 0xae, 0xd9, 0x00, 0x76,
	0xe2, 0x7c, 0x0e, 0xaa, 0x3e, 0x45, 0x11, 0xe3, 0x86, 0x81, 0x16, 0x63, 0xd7, 0xcf, 0xdb, 0x5a,
	0xdd, 0x0c, 0x77, 0xd6, 0x84, 0x32, 0x9d, 0x09, 0xc0, 0x42, 0x88, 0x05, 0xc2, 0x34, 0xf4, 0xd3,
	0x21, 0x26, 0x9c, 0x29, 0x3d, 0x8b, 0x5f, 0x33, 0x7c, 0x7d, 0x14, 0x4f, 0x0b, 0x04, 0x7c, 0x1b,
	0xc0, 0xcc, 0x16, 0x97, 0x03, 0x33, 0x40, 0x8a, 0xba, 0x69, 0xf3, 0xc3, 0xf5, 0xfd, 0x70, 0xa0,
	0xc7, 0xc7, 0x6d, 0x70, 0x39, 0x6f, 0xcc, 0x12, 0x19, 0x27, 0xd2, 0x23, 0x34, 0xc4, 0x03, 0xdd,
	0xba, 0x9a, 0xbb, 0x94, 0x71, 0xfa, 0x44, 0xab, 0xf7, 0x95, 0x16, 0x3e, 0x02, 0xb5, 0x80, 0x93,
	0xb0, 0x83, 0xd3, 0x44, 0xc0, 0x9b, 0x24, 0x52, 0x35, 0xb1, 0x6c, 0x12, 0x5f, 0x80, 0x05, 0x8a,
	0x1f, 0x7b, 0xb9, 0xad, 0xa5, 0x37, 0xfc, 0x6b, 0x2c, 0xad, 0x79, 0x8a, 0x1f, 0xe7, 0xde, 0xee,
	0xd7, 0x40, 0x8d, 0x88, 0xcc, 0x32, 0xd0, 0x0f, 0x82, 0xb2, 0x5b, 0x25, 0x62, 0xb4, 0x02, 0x86,
	0x30, 0x9c, 0xae, 0x97, 0x34, 0x0c, 0xc1, 0xce, 0x93, 0xc2, 0xd3, 0x93, 0x95, 0xc2, 0xb3, 0x93,
	0x95, 0xc2, 0xef, 0x27, 0x2b, 0x85, 0x6f, 0x5f, 0xac, 0x4c, 0x3c, 0x7b, 0xb1, 0x32, 0xf1, 0xeb,
	0x8b, 0x95, 0x89, 0x47, 0xb4, 0x43, 0x64, 0x94, 0x04, 0x0d, 0xc4, 0x7a, 0x4d, 0xe4, 0xf3, 0xd0,
	0xa7, 0x6c, 0xb3, 0xcd, 0x12, 0x1a, 0xea, 0xd7, 0xdc, 0x50, 0x44, 0x02, 0xb4, 0x49, 0x28, 0x4a,
	0x02, 0x5f, 0x32, 0xde, 0x44, 0x4c, 0xf4, 0x98, 0x18, 0x2a, 0x73, 0x49, 0x6c, 0xea, 0xfc, 0x36,
	0x4d, 0x82, 0x9b, 0xfd, 0x5b, 0xef, 0xe7, 0xb4, 0x41, 0x49, 0xbf, 0x18, 0xdf, 0xfd, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0x56, 0x2d, 0x82, 0x33, 0x0e, 0x00, 0x00,
}

func (m *Height) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Height) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Height) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevisionHeight != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.RevisionHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.RevisionNumber != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.RevisionNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StakeDistributionEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakeDistributionEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakeDistributionEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FirstRegistrationSlot != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.FirstRegistrationSlot))
		i--
		dAtA[i] = 0x20
	}
	if len(m.VrfKeyHash) > 0 {
		i -= len(m.VrfKeyHash)
		copy(dAtA[i:], m.VrfKeyHash)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.VrfKeyHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Stake != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.Stake))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochContext) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochContext) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochContext) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochEndSlotExclusive != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.EpochEndSlotExclusive))
		i--
		dAtA[i] = 0x30
	}
	if m.EpochStartSlot != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.EpochStartSlot))
		i--
		dAtA[i] = 0x28
	}
	if m.SlotsPerKesPeriod != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.SlotsPerKesPeriod))
		i--
		dAtA[i] = 0x20
	}
	if len(m.EpochNonce) > 0 {
		i -= len(m.EpochNonce)
		copy(dAtA[i:], m.EpochNonce)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.EpochNonce)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StakeDistribution) > 0 {
		for iNdEx := len(m.StakeDistribution) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakeDistribution[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProbabilistic(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Epoch != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestCheckpointEpoch != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.LatestCheckpointEpoch))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if len(m.LatestCheckpointBlockHash) > 0 {
		i -= len(m.LatestCheckpointBlockHash)
		copy(dAtA[i:], m.LatestCheckpointBlockHash)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.LatestCheckpointBlockHash)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.LatestCheckpointHeight != nil {
		{
			size, err := m.LatestCheckpointHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.EpochContexts) > 0 {
		for iNdEx := len(m.EpochContexts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochContexts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProbabilistic(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if m.SlotLengthNs != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.SlotLengthNs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.SystemStartUnixNs != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.SystemStartUnixNs))
		i--
		dAtA[i] = 0x78
	}
	if m.CurrentEpochEndSlotExclusive != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.CurrentEpochEndSlotExclusive))
		i--
		dAtA[i] = 0x70
	}
	if m.CurrentEpochStartSlot != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.CurrentEpochStartSlot))
		i--
		dAtA[i] = 0x68
	}
	if m.SlotsPerKesPeriod != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.SlotsPerKesPeriod))
		i--
		dAtA[i] = 0x60
	}
	if len(m.EpochNonce) > 0 {
		i -= len(m.EpochNonce)
		copy(dAtA[i:], m.EpochNonce)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.EpochNonce)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.EpochStakeDistribution) > 0 {
		for iNdEx := len(m.EpochStakeDistribution) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochStakeDistribution[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProbabilistic(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.HostStateNftTokenName) > 0 {
		i -= len(m.HostStateNftTokenName)
		copy(dAtA[i:], m.HostStateNftTokenName)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.HostStateNftTokenName)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.HostStateNftPolicyId) > 0 {
		i -= len(m.HostStateNftPolicyId)
		copy(dAtA[i:], m.HostStateNftPolicyId)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.HostStateNftPolicyId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.UpgradePath) > 0 {
		for iNdEx := len(m.UpgradePath) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.UpgradePath[iNdEx])
			copy(dAtA[i:], m.UpgradePath[iNdEx])
			i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.UpgradePath[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintProbabilistic(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if m.CurrentEpoch != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.FrozenHeight != nil {
		{
			size, err := m.FrozenHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.LatestHeight != nil {
		{
			size, err := m.LatestHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SecurityScoreBps != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.SecurityScoreBps))
		i--
		dAtA[i] = 0x38
	}
	if m.UniqueStakeBps != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.UniqueStakeBps))
		i--
		dAtA[i] = 0x30
	}
	if m.UniquePoolsCount != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.UniquePoolsCount))
		i--
		dAtA[i] = 0x28
	}
	if m.AcceptedEpoch != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.AcceptedEpoch))
		i--
		dAtA[i] = 0x20
	}
	if len(m.AcceptedBlockHash) > 0 {
		i -= len(m.AcceptedBlockHash)
		copy(dAtA[i:], m.AcceptedBlockHash)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.AcceptedBlockHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.IbcStateRoot) > 0 {
		i -= len(m.IbcStateRoot)
		copy(dAtA[i:], m.IbcStateRoot)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.IbcStateRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.Timestamp != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProbabilisticHeader2 != nil {
		{
			size, err := m.ProbabilisticHeader2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ProbabilisticHeader1 != nil {
		{
			size, err := m.ProbabilisticHeader1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProbabilisticBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProbabilisticBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProbabilisticBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlockCbor) > 0 {
		i -= len(m.BlockCbor)
		copy(dAtA[i:], m.BlockCbor)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.BlockCbor)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Timestamp != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.Epoch != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Slot != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != nil {
		{
			size, err := m.Height.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProbabilisticHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProbabilisticHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProbabilisticHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsCheckpoint {
		i--
		if m.IsCheckpoint {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.NewEpochContext != nil {
		{
			size, err := m.NewEpochContext.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.BridgeBlocks) > 0 {
		for iNdEx := len(m.BridgeBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BridgeBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProbabilistic(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.HostStateTxOutputIndex != 0 {
		i = encodeVarintProbabilistic(dAtA, i, uint64(m.HostStateTxOutputIndex))
		i--
		dAtA[i] = 0x30
	}
	if len(m.HostStateTxHash) > 0 {
		i -= len(m.HostStateTxHash)
		copy(dAtA[i:], m.HostStateTxHash)
		i = encodeVarintProbabilistic(dAtA, i, uint64(len(m.HostStateTxHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DescendantBlocks) > 0 {
		for iNdEx := len(m.DescendantBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DescendantBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProbabilistic(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AnchorBlock != nil {
		{
			size, err := m.AnchorBlock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TrustedHeight != nil {
		{
			size, err := m.TrustedHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProbabilistic(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProbabilistic(dAtA []byte, offset int, v uint64) int {
	offset -= sovProbabilistic(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Height) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RevisionNumber != 0 {
		n += 1 + sovProbabilistic(uint64(m.RevisionNumber))
	}
	if m.RevisionHeight != 0 {
		n += 1 + sovProbabilistic(uint64(m.RevisionHeight))
	}
	return n
}

func (m *StakeDistributionEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.Stake != 0 {
		n += 1 + sovProbabilistic(uint64(m.Stake))
	}
	l = len(m.VrfKeyHash)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.FirstRegistrationSlot != 0 {
		n += 1 + sovProbabilistic(uint64(m.FirstRegistrationSlot))
	}
	return n
}

func (m *EpochContext) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovProbabilistic(uint64(m.Epoch))
	}
	if len(m.StakeDistribution) > 0 {
		for _, e := range m.StakeDistribution {
			l = e.Size()
			n += 1 + l + sovProbabilistic(uint64(l))
		}
	}
	l = len(m.EpochNonce)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.SlotsPerKesPeriod != 0 {
		n += 1 + sovProbabilistic(uint64(m.SlotsPerKesPeriod))
	}
	if m.EpochStartSlot != 0 {
		n += 1 + sovProbabilistic(uint64(m.EpochStartSlot))
	}
	if m.EpochEndSlotExclusive != 0 {
		n += 1 + sovProbabilistic(uint64(m.EpochEndSlotExclusive))
	}
	return n
}

func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.LatestHeight != nil {
		l = m.LatestHeight.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.FrozenHeight != nil {
		l = m.FrozenHeight.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.CurrentEpoch != 0 {
		n += 1 + sovProbabilistic(uint64(m.CurrentEpoch))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovProbabilistic(uint64(l))
	if len(m.UpgradePath) > 0 {
		for _, s := range m.UpgradePath {
			l = len(s)
			n += 1 + l + sovProbabilistic(uint64(l))
		}
	}
	l = len(m.HostStateNftPolicyId)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	l = len(m.HostStateNftTokenName)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if len(m.EpochStakeDistribution) > 0 {
		for _, e := range m.EpochStakeDistribution {
			l = e.Size()
			n += 1 + l + sovProbabilistic(uint64(l))
		}
	}
	l = len(m.EpochNonce)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.SlotsPerKesPeriod != 0 {
		n += 1 + sovProbabilistic(uint64(m.SlotsPerKesPeriod))
	}
	if m.CurrentEpochStartSlot != 0 {
		n += 1 + sovProbabilistic(uint64(m.CurrentEpochStartSlot))
	}
	if m.CurrentEpochEndSlotExclusive != 0 {
		n += 1 + sovProbabilistic(uint64(m.CurrentEpochEndSlotExclusive))
	}
	if m.SystemStartUnixNs != 0 {
		n += 1 + sovProbabilistic(uint64(m.SystemStartUnixNs))
	}
	if m.SlotLengthNs != 0 {
		n += 2 + sovProbabilistic(uint64(m.SlotLengthNs))
	}
	if len(m.EpochContexts) > 0 {
		for _, e := range m.EpochContexts {
			l = e.Size()
			n += 2 + l + sovProbabilistic(uint64(l))
		}
	}
	if m.LatestCheckpointHeight != nil {
		l = m.LatestCheckpointHeight.Size()
		n += 2 + l + sovProbabilistic(uint64(l))
	}
	l = len(m.LatestCheckpointBlockHash)
	if l > 0 {
		n += 2 + l + sovProbabilistic(uint64(l))
	}
	if m.LatestCheckpointEpoch != 0 {
		n += 2 + sovProbabilistic(uint64(m.LatestCheckpointEpoch))
	}
	return n
}

func (m *ConsensusState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovProbabilistic(uint64(m.Timestamp))
	}
	l = len(m.IbcStateRoot)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	l = len(m.AcceptedBlockHash)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.AcceptedEpoch != 0 {
		n += 1 + sovProbabilistic(uint64(m.AcceptedEpoch))
	}
	if m.UniquePoolsCount != 0 {
		n += 1 + sovProbabilistic(uint64(m.UniquePoolsCount))
	}
	if m.UniqueStakeBps != 0 {
		n += 1 + sovProbabilistic(uint64(m.UniqueStakeBps))
	}
	if m.SecurityScoreBps != 0 {
		n += 1 + sovProbabilistic(uint64(m.SecurityScoreBps))
	}
	return n
}

func (m *Misbehaviour) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.ProbabilisticHeader1 != nil {
		l = m.ProbabilisticHeader1.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.ProbabilisticHeader2 != nil {
		l = m.ProbabilisticHeader2.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	return n
}

func (m *ProbabilisticBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != nil {
		l = m.Height.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.Slot != 0 {
		n += 1 + sovProbabilistic(uint64(m.Slot))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovProbabilistic(uint64(m.Epoch))
	}
	if m.Timestamp != 0 {
		n += 1 + sovProbabilistic(uint64(m.Timestamp))
	}
	l = len(m.BlockCbor)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	return n
}

func (m *ProbabilisticHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustedHeight != nil {
		l = m.TrustedHeight.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.AnchorBlock != nil {
		l = m.AnchorBlock.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if len(m.DescendantBlocks) > 0 {
		for _, e := range m.DescendantBlocks {
			l = e.Size()
			n += 1 + l + sovProbabilistic(uint64(l))
		}
	}
	l = len(m.HostStateTxHash)
	if l > 0 {
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.HostStateTxOutputIndex != 0 {
		n += 1 + sovProbabilistic(uint64(m.HostStateTxOutputIndex))
	}
	if len(m.BridgeBlocks) > 0 {
		for _, e := range m.BridgeBlocks {
			l = e.Size()
			n += 1 + l + sovProbabilistic(uint64(l))
		}
	}
	if m.NewEpochContext != nil {
		l = m.NewEpochContext.Size()
		n += 1 + l + sovProbabilistic(uint64(l))
	}
	if m.IsCheckpoint {
		n += 2
	}
	return n
}

func sovProbabilistic(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProbabilistic(x uint64) (n int) {
	return sovProbabilistic(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Height) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Height: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Height: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionNumber", wireType)
			}
			m.RevisionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionHeight", wireType)
			}
			m.RevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakeDistributionEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakeDistributionEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakeDistributionEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stake", wireType)
			}
			m.Stake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfKeyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfKeyHash = append(m.VrfKeyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.VrfKeyHash == nil {
				m.VrfKeyHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstRegistrationSlot", wireType)
			}
			m.FirstRegistrationSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstRegistrationSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochContext) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochContext: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochContext: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakeDistribution = append(m.StakeDistribution, &StakeDistributionEntry{})
			if err := m.StakeDistribution[len(m.StakeDistribution)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochNonce = append(m.EpochNonce[:0], dAtA[iNdEx:postIndex]...)
			if m.EpochNonce == nil {
				m.EpochNonce = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotsPerKesPeriod", wireType)
			}
			m.SlotsPerKesPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotsPerKesPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartSlot", wireType)
			}
			m.EpochStartSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochStartSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochEndSlotExclusive", wireType)
			}
			m.EpochEndSlotExclusive = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochEndSlotExclusive |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestHeight == nil {
				m.LatestHeight = &Height{}
			}
			if err := m.LatestHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrozenHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FrozenHeight == nil {
				m.FrozenHeight = &Height{}
			}
			if err := m.FrozenHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpgradePath = append(m.UpgradePath, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateNftPolicyId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateNftPolicyId = append(m.HostStateNftPolicyId[:0], dAtA[iNdEx:postIndex]...)
			if m.HostStateNftPolicyId == nil {
				m.HostStateNftPolicyId = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateNftTokenName", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateNftTokenName = append(m.HostStateNftTokenName[:0], dAtA[iNdEx:postIndex]...)
			if m.HostStateNftTokenName == nil {
				m.HostStateNftTokenName = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStakeDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochStakeDistribution = append(m.EpochStakeDistribution, &StakeDistributionEntry{})
			if err := m.EpochStakeDistribution[len(m.EpochStakeDistribution)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochNonce = append(m.EpochNonce[:0], dAtA[iNdEx:postIndex]...)
			if m.EpochNonce == nil {
				m.EpochNonce = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotsPerKesPeriod", wireType)
			}
			m.SlotsPerKesPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotsPerKesPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochStartSlot", wireType)
			}
			m.CurrentEpochStartSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpochStartSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochEndSlotExclusive", wireType)
			}
			m.CurrentEpochEndSlotExclusive = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpochEndSlotExclusive |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemStartUnixNs", wireType)
			}
			m.SystemStartUnixNs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SystemStartUnixNs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotLengthNs", wireType)
			}
			m.SlotLengthNs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotLengthNs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochContexts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochContexts = append(m.EpochContexts, &EpochContext{})
			if err := m.EpochContexts[len(m.EpochContexts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestCheckpointHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestCheckpointHeight == nil {
				m.LatestCheckpointHeight = &Height{}
			}
			if err := m.LatestCheckpointHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestCheckpointBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestCheckpointBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestCheckpointEpoch", wireType)
			}
			m.LatestCheckpointEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestCheckpointEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcStateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcStateRoot = append(m.IbcStateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcStateRoot == nil {
				m.IbcStateRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedEpoch", wireType)
			}
			m.AcceptedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcceptedEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniquePoolsCount", wireType)
			}
			m.UniquePoolsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniquePoolsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueStakeBps", wireType)
			}
			m.UniqueStakeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniqueStakeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityScoreBps", wireType)
			}
			m.SecurityScoreBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecurityScoreBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Misbehaviour) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Misbehaviour: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Misbehaviour: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProbabilisticHeader1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProbabilisticHeader1 == nil {
				m.ProbabilisticHeader1 = &ProbabilisticHeader{}
			}
			if err := m.ProbabilisticHeader1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProbabilisticHeader2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProbabilisticHeader2 == nil {
				m.ProbabilisticHeader2 = &ProbabilisticHeader{}
			}
			if err := m.ProbabilisticHeader2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProbabilisticBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProbabilisticBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProbabilisticBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Height == nil {
				m.Height = &Height{}
			}
			if err := m.Height.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockCbor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockCbor = append(m.BlockCbor[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockCbor == nil {
				m.BlockCbor = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProbabilisticHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProbabilisticHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProbabilisticHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustedHeight == nil {
				m.TrustedHeight = &Height{}
			}
			if err := m.TrustedHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnchorBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AnchorBlock == nil {
				m.AnchorBlock = &ProbabilisticBlock{}
			}
			if err := m.AnchorBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DescendantBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DescendantBlocks = append(m.DescendantBlocks, &ProbabilisticBlock{})
			if err := m.DescendantBlocks[len(m.DescendantBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateTxOutputIndex", wireType)
			}
			m.HostStateTxOutputIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HostStateTxOutputIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeBlocks = append(m.BridgeBlocks, &ProbabilisticBlock{})
			if err := m.BridgeBlocks[len(m.BridgeBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewEpochContext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProbabilistic
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NewEpochContext == nil {
				m.NewEpochContext = &EpochContext{}
			}
			if err := m.NewEpochContext.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsCheckpoint", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsCheckpoint = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipProbabilistic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProbabilistic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProbabilistic(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProbabilistic
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProbabilistic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProbabilistic
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProbabilistic
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProbabilistic
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProbabilistic        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProbabilistic          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProbabilistic = fmt.Errorf("proto: unexpected end of group")
)
