import {
  EVENT_TYPE_CONNECTION,
  ATTRIBUTE_KEY_CONNECTION,
  STATE_MAPPING_CONNECTION,
  CONNECTION_ID_PREFIX,
  KEY_CONNECTION_PREFIX,
} from "./connection";
import {
  EVENT_TYPE_CHANNEL,
  ATTRIBUTE_KEY_CHANNEL,
  CHANNEL_ID_PREFIX,
  PORT_ID_PREFIX,
  TRANSFER_MODULE_PORT,
  KEY_CHANNEL_PREFIX,
  KEY_PORT_PREFIX,
  KEY_CHANNEL_END_PREFIX,
  MOCK_MODULE_PORT,
  ORDER_MAPPING_CHANNEL,
} from "./channel";
import {
  EVENT_TYPE_CLIENT,
  ATTRIBUTE_KEY_CLIENT,
  CLIENT_ID_PREFIX,
  KEY_CLIENT_PREFIX,
  KEY_CLIENT_STATE,
  MAX_CONSENSUS_STATE_SIZE,
} from "./client";
import { EVENT_TYPE_SPO } from "./spo";
import { REDEEMER_EMPTY_DATA, REDEEMER_TYPE } from "./redeemer";
import {
  EVENT_TYPE_PACKET,
  ATTRIBUTE_KEY_PACKET,
  KEY_PACKET_ACK_PREFIX,
  KEY_PACKET_COMMITMENT_PREFIX,
  KEY_PACKET_RECEIPT_PREFIX,
  KEY_SEQUENCE_PREFIX,
} from "./packet";
import {
  BLOCKID_FLAG_ABSENT,
  BLOCKID_FLAG_COMMIT,
  BLOCKID_FLAG_NIL,
  CRYPTO_ADDRESS_SIZE,
  MAX_SIGNATURE_SIZE,
  MAX_CHAIN_ID_LENGTH,
  TM_HASH_SIZE,
} from "./block";

export const HANDLER_TOKEN_NAME = "68616e646c6572"; // fromText("handler")
export const CLIENT_PREFIX = "6962635f636c69656e74"; // fromText("ibc_client")
export const CONNECTION_TOKEN_PREFIX = "636f6e6e656374696f6e"; // fromText("connection")
export const CHANNEL_TOKEN_PREFIX = "6368616e6e656c"; // fromText("channel")
export const DEFAULT_IDENTIFIER_VERSION = "31"; // fromText("1")
export const DEFAULT_FEATURES_VERSION_ORDER_ORDERED = "4f524445525f4f524445524544"; // fromText("ORDER_ORDERED")
export const DEFAULT_FEATURES_VERSION_ORDER_UNORDERED = "4f524445525f554e4f524445524544"; // fromText("connection")
export const DEFAULT_MERKLE_PREFIX = "696263"; // fromText("ibc")
export const ACK_RESULT = "AQ==";

export const LOVELACE = "lovelace";

export const EMULATOR_ENV = "emulator";

export const MAX_EXPECTED_TIME_PER_BLOCK = 4000000000;

export {
  EVENT_TYPE_CONNECTION,
  ATTRIBUTE_KEY_CONNECTION,
  STATE_MAPPING_CONNECTION,
  CONNECTION_ID_PREFIX,
  KEY_CONNECTION_PREFIX,
  EVENT_TYPE_CHANNEL,
  ATTRIBUTE_KEY_CHANNEL,
  CHANNEL_ID_PREFIX,
  PORT_ID_PREFIX,
  TRANSFER_MODULE_PORT,
  MOCK_MODULE_PORT,
  KEY_CHANNEL_PREFIX,
  KEY_CHANNEL_END_PREFIX,
  ORDER_MAPPING_CHANNEL,
  KEY_PORT_PREFIX,
  REDEEMER_TYPE,
  REDEEMER_EMPTY_DATA,
  EVENT_TYPE_CLIENT,
  ATTRIBUTE_KEY_CLIENT,
  CLIENT_ID_PREFIX,
  KEY_CLIENT_PREFIX,
  KEY_CLIENT_STATE,
  MAX_CONSENSUS_STATE_SIZE,
  EVENT_TYPE_SPO,
  EVENT_TYPE_PACKET,
  ATTRIBUTE_KEY_PACKET,
  KEY_PACKET_ACK_PREFIX,
  KEY_PACKET_COMMITMENT_PREFIX,
  KEY_PACKET_RECEIPT_PREFIX,
  KEY_SEQUENCE_PREFIX,
  // block
  BLOCKID_FLAG_ABSENT,
  BLOCKID_FLAG_COMMIT,
  BLOCKID_FLAG_NIL,
  CRYPTO_ADDRESS_SIZE,
  MAX_SIGNATURE_SIZE,
  MAX_CHAIN_ID_LENGTH,
  TM_HASH_SIZE,
};
