services:
  osmosisd:
    image: local:osmosis
    build:
      context: ../osmosis
      dockerfile: Dockerfile
      args:
        RUNNER_IMAGE: alpine:3.19
        GO_VERSION: "1.23"
    volumes:
      - ../osmosis/tests/localosmosis/scripts/uosmoUionBalancerPool.json:/osmosis/uosmoUionBalancerPool.json
      - ../osmosis/tests/localosmosis/scripts/uosmoUusdcBalancerPool.json:/osmosis/uosmoUusdcBalancerPool.json
      - ../osmosis/tests/localosmosis/scripts/uusdcUionBalancerPool.json:/osmosis/uusdcUionBalancerPool.json
      - ../osmosis/tests/localosmosis/scripts/uwethUusdcStablePool.json:/osmosis/uwethUusdcStablePool.json
      - ../osmosis/tests/localosmosis/scripts/nativeDenomThreeAssetPool.json:/osmosis/nativeDenomThreeAssetPool.json
      - ../scripts/setup_osmosis_local.sh:/osmosis/setup.sh:ro
      - ../osmosis/tests/cl-genesis-positions:/osmosis/cl-genesis-positions
      - $HOME/.osmosisd-local/:/osmosis/.osmosisd/
    entrypoint: ["/osmosis/setup.sh"]
    ports:
      - 26658:26657
      - 1318:1317
      - 9094:9090
      - 9091:9091
      - 6060:6060
      - 9092:9092
    depends_on:
      - redis
    restart: unless-stopped
  # Enable Redis for sidecar query server
  redis:
    image: redis/redis-stack:7.2.0-v3
    volumes:
      - ./redis-data:/data
