[package]
name = "eureka-guest-runner"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
alloy-sol-types = "=1.5.7"
anyhow = "=1.0.102"
hex = "=0.4.3"
ibc-proto = { version = "=0.51.1", default-features = false }
prost = "=0.13.5"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
sha2 = "=0.10.9"
sp1-sdk = { version = "=6.1.0", default-features = false }
tendermint = { version = "=0.40.4", features = ["rust-crypto"] }
tendermint-rpc = "=0.40.4"
tendermint-testgen = "=0.40.4"
tokio = { version = "=1.52.1", features = ["macros", "rt-multi-thread"] }
