// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/stability/v1/stability.proto

package stability

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Height struct {
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	RevisionHeight uint64 `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
}

func (m *Height) Reset()         { *m = Height{} }
func (m Height) String() string { return proto.CompactTextString(&m) }
func (*Height) ProtoMessage()    {}
func (*Height) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{0}
}
func (m *Height) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Height) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Height.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Height) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Height.Merge(m, src)
}
func (m *Height) XXX_Size() int {
	return m.Size()
}
func (m *Height) XXX_DiscardUnknown() {
	xxx_messageInfo_Height.DiscardUnknown(m)
}

var xxx_messageInfo_Height proto.InternalMessageInfo

type HeuristicParams struct {
	MinDepth             uint64 `protobuf:"varint,1,opt,name=min_depth,json=minDepth,proto3" json:"min_depth,omitempty"`
	MinUniquePools       uint64 `protobuf:"varint,2,opt,name=min_unique_pools,json=minUniquePools,proto3" json:"min_unique_pools,omitempty"`
	MinUniqueStakeBps    uint64 `protobuf:"varint,3,opt,name=min_unique_stake_bps,json=minUniqueStakeBps,proto3" json:"min_unique_stake_bps,omitempty"`
	TargetDepth          uint64 `protobuf:"varint,4,opt,name=target_depth,json=targetDepth,proto3" json:"target_depth,omitempty"`
	TargetUniquePools    uint64 `protobuf:"varint,5,opt,name=target_unique_pools,json=targetUniquePools,proto3" json:"target_unique_pools,omitempty"`
	TargetUniqueStakeBps uint64 `protobuf:"varint,6,opt,name=target_unique_stake_bps,json=targetUniqueStakeBps,proto3" json:"target_unique_stake_bps,omitempty"`
	DepthWeightBps       uint64 `protobuf:"varint,7,opt,name=depth_weight_bps,json=depthWeightBps,proto3" json:"depth_weight_bps,omitempty"`
	PoolsWeightBps       uint64 `protobuf:"varint,8,opt,name=pools_weight_bps,json=poolsWeightBps,proto3" json:"pools_weight_bps,omitempty"`
	StakeWeightBps       uint64 `protobuf:"varint,9,opt,name=stake_weight_bps,json=stakeWeightBps,proto3" json:"stake_weight_bps,omitempty"`
}

func (m *HeuristicParams) Reset()         { *m = HeuristicParams{} }
func (m *HeuristicParams) String() string { return proto.CompactTextString(m) }
func (*HeuristicParams) ProtoMessage()    {}
func (*HeuristicParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{1}
}
func (m *HeuristicParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeuristicParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeuristicParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeuristicParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeuristicParams.Merge(m, src)
}
func (m *HeuristicParams) XXX_Size() int {
	return m.Size()
}
func (m *HeuristicParams) XXX_DiscardUnknown() {
	xxx_messageInfo_HeuristicParams.DiscardUnknown(m)
}

var xxx_messageInfo_HeuristicParams proto.InternalMessageInfo

type StakeDistributionEntry struct {
	PoolId string `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Stake  uint64 `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
}

func (m *StakeDistributionEntry) Reset()         { *m = StakeDistributionEntry{} }
func (m *StakeDistributionEntry) String() string { return proto.CompactTextString(m) }
func (*StakeDistributionEntry) ProtoMessage()    {}
func (*StakeDistributionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{2}
}
func (m *StakeDistributionEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakeDistributionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakeDistributionEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakeDistributionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeDistributionEntry.Merge(m, src)
}
func (m *StakeDistributionEntry) XXX_Size() int {
	return m.Size()
}
func (m *StakeDistributionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeDistributionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StakeDistributionEntry proto.InternalMessageInfo

type ClientState struct {
	ChainId                string                    `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	LatestHeight           *Height                   `protobuf:"bytes,2,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	FrozenHeight           *Height                   `protobuf:"bytes,3,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	CurrentEpoch           uint64                    `protobuf:"varint,4,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	TrustingPeriod         time.Duration             `protobuf:"bytes,5,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	HeuristicParams        *HeuristicParams          `protobuf:"bytes,6,opt,name=heuristic_params,json=heuristicParams,proto3" json:"heuristic_params,omitempty"`
	UpgradePath            []string                  `protobuf:"bytes,7,rep,name=upgrade_path,json=upgradePath,proto3" json:"upgrade_path,omitempty"`
	HostStateNftPolicyId   []byte                    `protobuf:"bytes,8,opt,name=host_state_nft_policy_id,json=hostStateNftPolicyId,proto3" json:"host_state_nft_policy_id,omitempty"`
	HostStateNftTokenName  []byte                    `protobuf:"bytes,9,opt,name=host_state_nft_token_name,json=hostStateNftTokenName,proto3" json:"host_state_nft_token_name,omitempty"`
	EpochStakeDistribution []*StakeDistributionEntry `protobuf:"bytes,10,rep,name=epoch_stake_distribution,json=epochStakeDistribution,proto3" json:"epoch_stake_distribution,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{3}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type ConsensusState struct {
	Timestamp         uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IbcStateRoot      []byte `protobuf:"bytes,2,opt,name=ibc_state_root,json=ibcStateRoot,proto3" json:"ibc_state_root,omitempty"`
	AcceptedBlockHash string `protobuf:"bytes,3,opt,name=accepted_block_hash,json=acceptedBlockHash,proto3" json:"accepted_block_hash,omitempty"`
	AcceptedEpoch     uint64 `protobuf:"varint,4,opt,name=accepted_epoch,json=acceptedEpoch,proto3" json:"accepted_epoch,omitempty"`
	UniquePoolsCount  uint64 `protobuf:"varint,5,opt,name=unique_pools_count,json=uniquePoolsCount,proto3" json:"unique_pools_count,omitempty"`
	UniqueStakeBps    uint64 `protobuf:"varint,6,opt,name=unique_stake_bps,json=uniqueStakeBps,proto3" json:"unique_stake_bps,omitempty"`
	SecurityScoreBps  uint64 `protobuf:"varint,7,opt,name=security_score_bps,json=securityScoreBps,proto3" json:"security_score_bps,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{4}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

type Misbehaviour struct {
	ClientId         string           `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Deprecated: Do not use.
	StabilityHeader1 *StabilityHeader `protobuf:"bytes,2,opt,name=stability_header_1,json=stabilityHeader1,proto3" json:"stability_header_1,omitempty"`
	StabilityHeader2 *StabilityHeader `protobuf:"bytes,3,opt,name=stability_header_2,json=stabilityHeader2,proto3" json:"stability_header_2,omitempty"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{5}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return m.Size()
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

type StabilityBlock struct {
	Height     *Height `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Slot       uint64  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Hash       string  `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevHash   string  `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Epoch      uint64  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Timestamp  uint64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SlotLeader string  `protobuf:"bytes,7,opt,name=slot_leader,json=slotLeader,proto3" json:"slot_leader,omitempty"`
	StakeBps   uint64  `protobuf:"varint,8,opt,name=stake_bps,json=stakeBps,proto3" json:"stake_bps,omitempty"`
}

func (m *StabilityBlock) Reset()         { *m = StabilityBlock{} }
func (m *StabilityBlock) String() string { return proto.CompactTextString(m) }
func (*StabilityBlock) ProtoMessage()    {}
func (*StabilityBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{6}
}
func (m *StabilityBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StabilityBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StabilityBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StabilityBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StabilityBlock.Merge(m, src)
}
func (m *StabilityBlock) XXX_Size() int {
	return m.Size()
}
func (m *StabilityBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_StabilityBlock.DiscardUnknown(m)
}

var xxx_messageInfo_StabilityBlock proto.InternalMessageInfo

type StabilityHeader struct {
	TrustedHeight          *Height           `protobuf:"bytes,1,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height,omitempty"`
	AnchorBlock            *StabilityBlock   `protobuf:"bytes,2,opt,name=anchor_block,json=anchorBlock,proto3" json:"anchor_block,omitempty"`
	DescendantBlocks       []*StabilityBlock `protobuf:"bytes,3,rep,name=descendant_blocks,json=descendantBlocks,proto3" json:"descendant_blocks,omitempty"`
	HostStateTxHash        string            `protobuf:"bytes,4,opt,name=host_state_tx_hash,json=hostStateTxHash,proto3" json:"host_state_tx_hash,omitempty"`
	HostStateTxBodyCbor    []byte            `protobuf:"bytes,5,opt,name=host_state_tx_body_cbor,json=hostStateTxBodyCbor,proto3" json:"host_state_tx_body_cbor,omitempty"`
	HostStateTxOutputIndex uint32            `protobuf:"varint,6,opt,name=host_state_tx_output_index,json=hostStateTxOutputIndex,proto3" json:"host_state_tx_output_index,omitempty"`
	UniquePoolsCount       uint64            `protobuf:"varint,7,opt,name=unique_pools_count,json=uniquePoolsCount,proto3" json:"unique_pools_count,omitempty"`
	UniqueStakeBps         uint64            `protobuf:"varint,8,opt,name=unique_stake_bps,json=uniqueStakeBps,proto3" json:"unique_stake_bps,omitempty"`
	SecurityScoreBps       uint64            `protobuf:"varint,9,opt,name=security_score_bps,json=securityScoreBps,proto3" json:"security_score_bps,omitempty"`
}

func (m *StabilityHeader) Reset()         { *m = StabilityHeader{} }
func (m *StabilityHeader) String() string { return proto.CompactTextString(m) }
func (*StabilityHeader) ProtoMessage()    {}
func (*StabilityHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_9994cc5c23484162, []int{7}
}
func (m *StabilityHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StabilityHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StabilityHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StabilityHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StabilityHeader.Merge(m, src)
}
func (m *StabilityHeader) XXX_Size() int {
	return m.Size()
}
func (m *StabilityHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_StabilityHeader.DiscardUnknown(m)
}

var xxx_messageInfo_StabilityHeader proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Height)(nil), "ibc.lightclients.stability.v1.Height")
	proto.RegisterType((*HeuristicParams)(nil), "ibc.lightclients.stability.v1.HeuristicParams")
	proto.RegisterType((*StakeDistributionEntry)(nil), "ibc.lightclients.stability.v1.StakeDistributionEntry")
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.stability.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.stability.v1.ConsensusState")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.stability.v1.Misbehaviour")
	proto.RegisterType((*StabilityBlock)(nil), "ibc.lightclients.stability.v1.StabilityBlock")
	proto.RegisterType((*StabilityHeader)(nil), "ibc.lightclients.stability.v1.StabilityHeader")
}

func init() {
	proto.RegisterFile("ibc/lightclients/stability/v1/stability.proto", fileDescriptor_9994cc5c23484162)
}

var fileDescriptor_9994cc5c23484162 = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x8e, 0x1b, 0x45,
	0x17, 0x1e, 0x8f, 0x3d, 0x1e, 0xfb, 0xf8, 0x9a, 0x8a, 0xff, 0xc4, 0xc9, 0x0f, 0x76, 0x12, 0x88,
	0x18, 0x89, 0xc4, 0xd6, 0x18, 0x82, 0xa2, 0x48, 0x6c, 0x3c, 0x89, 0x34, 0x13, 0x25, 0xc1, 0xea,
	0x04, 0x21, 0xb2, 0x69, 0xfa, 0x52, 0xe3, 0x2e, 0xc5, 0xee, 0x6a, 0xaa, 0xaa, 0x87, 0x31, 0x4f,
	0xc0, 0x82, 0x05, 0x3b, 0x10, 0x12, 0x12, 0x6f, 0x01, 0x8f, 0x90, 0x65, 0x96, 0xac, 0x02, 0x9a,
	0xbc, 0x08, 0xaa, 0x53, 0x65, 0xbb, 0xed, 0xdc, 0x18, 0xc4, 0xce, 0xf5, 0x9d, 0xef, 0x9c, 0xba,
	0x9c, 0xef, 0x7c, 0x6d, 0xb8, 0xce, 0xfc, 0xa0, 0x3f, 0x61, 0xe3, 0x48, 0x05, 0x13, 0x46, 0x63,
	0x25, 0xfb, 0x52, 0x79, 0x3e, 0x9b, 0x30, 0x35, 0xeb, 0x1f, 0xed, 0x2e, 0x17, 0xbd, 0x44, 0x70,
	0xc5, 0xc9, 0xbb, 0xcc, 0x0f, 0x7a, 0x59, 0x7a, 0x6f, 0xc9, 0x38, 0xda, 0xbd, 0xd8, 0x1a, 0xf3,
	0x31, 0x47, 0x66, 0x5f, 0xff, 0x32, 0x49, 0x17, 0x3b, 0x63, 0xce, 0xc7, 0x13, 0xda, 0xc7, 0x95,
	0x9f, 0x1e, 0xf6, 0xc3, 0x54, 0x78, 0x8a, 0xf1, 0xd8, 0xc4, 0xaf, 0x7c, 0x05, 0xc5, 0x7d, 0xaa,
	0x6b, 0x92, 0x0f, 0xa0, 0x21, 0xe8, 0x11, 0x93, 0x8c, 0xc7, 0x6e, 0x9c, 0x4e, 0x7d, 0x2a, 0xda,
	0xb9, 0x4b, 0xb9, 0x9d, 0x82, 0x53, 0x9f, 0xc3, 0x0f, 0x10, 0x5d, 0x21, 0x46, 0x98, 0xdb, 0xde,
	0x5c, 0x25, 0x9a, 0x8a, 0xb7, 0x0a, 0xdf, 0xfd, 0xda, 0xdd, 0xb8, 0xf2, 0x63, 0x1e, 0x1a, 0xfb,
	0x34, 0x15, 0x4c, 0x2a, 0x16, 0x8c, 0x3c, 0xe1, 0x4d, 0x25, 0xf9, 0x3f, 0x94, 0xa7, 0x2c, 0x76,
	0x43, 0x9a, 0xa8, 0xc8, 0xee, 0x52, 0x9a, 0xb2, 0xf8, 0xb6, 0x5e, 0x93, 0x1d, 0x68, 0xea, 0x60,
	0x1a, 0xb3, 0xaf, 0x53, 0xea, 0x26, 0x9c, 0x4f, 0xe4, 0x7c, 0x83, 0x29, 0x8b, 0x3f, 0x47, 0x78,
	0xa4, 0x51, 0xd2, 0x87, 0x56, 0x86, 0x29, 0x95, 0xf7, 0x84, 0xba, 0x7e, 0x22, 0xdb, 0x79, 0x64,
	0x9f, 0x59, 0xb0, 0x1f, 0xea, 0xc8, 0x30, 0x91, 0xe4, 0x32, 0x54, 0x95, 0x27, 0xc6, 0x54, 0xd9,
	0xad, 0x0b, 0x48, 0xac, 0x18, 0xcc, 0xec, 0xde, 0x83, 0xb3, 0x96, 0xb2, 0x72, 0x80, 0x2d, 0x53,
	0xd2, 0x84, 0xb2, 0x67, 0xb8, 0x01, 0xe7, 0x57, 0xf9, 0xcb, 0x63, 0x14, 0x31, 0xa7, 0x95, 0xcd,
	0x59, 0x9c, 0x64, 0x07, 0x9a, 0x78, 0x04, 0xf7, 0x1b, 0x7c, 0x2b, 0xe4, 0x6f, 0x9b, 0x4b, 0x22,
	0xfe, 0x05, 0xc2, 0x96, 0x89, 0x47, 0xc8, 0x32, 0x4b, 0x86, 0x89, 0xf8, 0x0a, 0xd3, 0x6c, 0x9e,
	0x61, 0x96, 0x0d, 0x13, 0xf1, 0x05, 0xd3, 0x76, 0xe6, 0x3e, 0x9c, 0xc3, 0xf3, 0xdc, 0x66, 0x52,
	0x09, 0xe6, 0xa7, 0x5a, 0x16, 0x77, 0x62, 0x25, 0x66, 0xe4, 0x3c, 0x6c, 0xeb, 0xda, 0x2e, 0x0b,
	0xb1, 0x3b, 0x65, 0xa7, 0xa8, 0x97, 0x07, 0x21, 0x69, 0xc1, 0x16, 0x96, 0xb2, 0x0d, 0x31, 0x0b,
	0x5b, 0xee, 0xe7, 0x2d, 0xa8, 0xec, 0xa1, 0x32, 0x1f, 0x2a, 0x4f, 0x51, 0x72, 0x01, 0x4a, 0x41,
	0xe4, 0xb1, 0x78, 0x59, 0x65, 0x1b, 0xd7, 0x07, 0x21, 0xb9, 0x0b, 0xb5, 0x89, 0xa7, 0xa8, 0x54,
	0x59, 0x01, 0x55, 0x06, 0x57, 0x7b, 0x6f, 0x94, 0x78, 0xcf, 0xe8, 0xca, 0xa9, 0x9a, 0x5c, 0xab,
	0xdb, 0xbb, 0x50, 0x3b, 0x14, 0xfc, 0x5b, 0xba, 0x10, 0x63, 0xfe, 0x54, 0xb5, 0x4c, 0xae, 0xad,
	0xf5, 0x1e, 0xd4, 0x82, 0x54, 0x08, 0x1a, 0x2b, 0x97, 0x26, 0x3c, 0x98, 0x0b, 0xa4, 0x6a, 0xc1,
	0x3b, 0x1a, 0x23, 0xf7, 0xa0, 0xa1, 0x44, 0x2a, 0x15, 0x8b, 0xc7, 0x6e, 0x42, 0x05, 0xe3, 0x21,
	0xaa, 0xa3, 0x32, 0xb8, 0xd0, 0x33, 0xc3, 0xd6, 0x9b, 0x0f, 0x5b, 0xef, 0xb6, 0x1d, 0xb6, 0x61,
	0xe9, 0xe9, 0xf3, 0xee, 0xc6, 0x4f, 0x7f, 0x76, 0x73, 0x4e, 0x7d, 0x9e, 0x3b, 0xc2, 0x54, 0xf2,
	0x25, 0x34, 0xa3, 0xf9, 0x74, 0xb8, 0x09, 0x8e, 0x07, 0x0a, 0xa7, 0x32, 0xe8, 0xbd, 0xf5, 0x06,
	0x2b, 0x43, 0xe5, 0x34, 0xa2, 0xb5, 0x29, 0xbb, 0x0c, 0xd5, 0x34, 0x19, 0x0b, 0x2f, 0xa4, 0x6e,
	0xe2, 0xa9, 0xa8, 0xbd, 0x7d, 0x29, 0xbf, 0x53, 0x76, 0x2a, 0x16, 0x1b, 0x79, 0x2a, 0x22, 0x9f,
	0x40, 0x3b, 0xe2, 0x52, 0x69, 0xd1, 0x2a, 0xea, 0xc6, 0x87, 0xca, 0x4d, 0xf8, 0x84, 0x05, 0x33,
	0xdd, 0x33, 0x2d, 0xb2, 0xaa, 0xd3, 0xd2, 0x71, 0x6c, 0xe8, 0x83, 0x43, 0x35, 0xc2, 0xe0, 0x41,
	0x48, 0x6e, 0xc2, 0x85, 0xb5, 0x3c, 0xc5, 0x9f, 0xd0, 0xd8, 0x8d, 0xbd, 0x29, 0x45, 0xcd, 0x55,
	0x9d, 0xff, 0x65, 0x13, 0x1f, 0xe9, 0xe8, 0x03, 0x6f, 0x4a, 0x09, 0x87, 0x36, 0x3e, 0xad, 0x9d,
	0x93, 0x30, 0xa3, 0xbd, 0x36, 0x5c, 0xca, 0xef, 0x54, 0x06, 0x37, 0xde, 0x72, 0xef, 0x57, 0x6b,
	0xd6, 0x39, 0x87, 0x65, 0x5f, 0x0a, 0x5a, 0x71, 0xfe, 0xb6, 0x09, 0xf5, 0x3d, 0x1e, 0x4b, 0x1a,
	0xcb, 0x54, 0x1a, 0x7d, 0xbe, 0x03, 0x65, 0xc5, 0xa6, 0x54, 0x2a, 0x6f, 0x9a, 0x58, 0x13, 0x5a,
	0x02, 0xe4, 0x7d, 0xa8, 0x33, 0x3f, 0xb0, 0x17, 0x14, 0x9c, 0x1b, 0x8d, 0x56, 0x9d, 0x2a, 0xf3,
	0x03, 0xcc, 0x77, 0x38, 0x57, 0xda, 0x2d, 0xbc, 0x20, 0xa0, 0x89, 0xa2, 0xa1, 0xeb, 0x4f, 0x78,
	0xf0, 0xc4, 0x8d, 0x3c, 0x19, 0xa1, 0x04, 0xcb, 0xce, 0x99, 0x79, 0x68, 0xa8, 0x23, 0xfb, 0x9e,
	0x8c, 0xc8, 0x55, 0xa8, 0x2f, 0xf8, 0x59, 0x85, 0xd5, 0xe6, 0xa8, 0x91, 0xd8, 0x35, 0x20, 0x59,
	0xf7, 0x71, 0x03, 0x9e, 0xc6, 0xca, 0x7a, 0x50, 0x33, 0x5d, 0xba, 0xcf, 0x9e, 0xc6, 0xf5, 0xdc,
	0xbf, 0xc6, 0x7b, 0xea, 0xe9, 0xaa, 0xeb, 0x5c, 0x03, 0x22, 0x69, 0x90, 0x0a, 0xa6, 0x66, 0xae,
	0x0c, 0xb8, 0xa0, 0x19, 0xdf, 0x69, 0xce, 0x23, 0x0f, 0x75, 0x60, 0xe9, 0x12, 0xbf, 0x6c, 0x42,
	0xf5, 0x3e, 0x93, 0x3e, 0x8d, 0xbc, 0x23, 0xc6, 0x53, 0x41, 0xba, 0x50, 0x36, 0x7d, 0x59, 0x0c,
	0xf6, 0x70, 0xb3, 0x9d, 0x73, 0x4a, 0x06, 0x3c, 0x08, 0x89, 0x00, 0xb2, 0x68, 0x98, 0x1b, 0x51,
	0x2f, 0xa4, 0xc2, 0xdd, 0xb5, 0x23, 0xde, 0x7b, 0x7b, 0x73, 0xcd, 0x62, 0x1f, 0xf3, 0x86, 0xad,
	0x93, 0xe7, 0xdd, 0xe6, 0x1a, 0xb8, 0xeb, 0x34, 0xe5, 0x1a, 0xf2, 0xca, 0x3d, 0x07, 0xd6, 0x0a,
	0xfe, 0x8b, 0x3d, 0x07, 0x2f, 0xed, 0x39, 0xb0, 0xef, 0xf3, 0xfd, 0x26, 0xd4, 0x17, 0x64, 0xec,
	0x34, 0xf9, 0x14, 0x8a, 0xd6, 0x8b, 0x72, 0xa7, 0xf1, 0x22, 0x9b, 0x44, 0x08, 0x14, 0xe4, 0x84,
	0xcf, 0xbf, 0xaa, 0xf8, 0x5b, 0x63, 0x19, 0x65, 0xe1, 0x6f, 0xfd, 0x15, 0x4d, 0x04, 0x3d, 0x32,
	0x92, 0x2b, 0x60, 0xa0, 0xa4, 0x01, 0x54, 0x5a, 0x0b, 0xb6, 0x8c, 0xc0, 0x8c, 0x6a, 0xcc, 0x62,
	0x55, 0xf3, 0xc5, 0x75, 0xcd, 0x77, 0xa1, 0xa2, 0x37, 0x73, 0x27, 0x78, 0x41, 0xd4, 0x45, 0xd9,
	0x01, 0x0d, 0xdd, 0x43, 0x44, 0xef, 0xb8, 0x94, 0x98, 0xf9, 0x08, 0x95, 0xa4, 0x15, 0x97, 0x7d,
	0x8e, 0xdf, 0x0b, 0xd0, 0x58, 0x7b, 0x3b, 0x72, 0x0f, 0x8c, 0xeb, 0xd1, 0xd0, 0xfd, 0x37, 0xef,
	0x52, 0xb3, 0xc9, 0xd6, 0xa4, 0x47, 0x50, 0xf5, 0xe2, 0x20, 0xe2, 0xc2, 0x4c, 0x9c, 0x15, 0xd6,
	0xf5, 0x7f, 0xda, 0x64, 0x6c, 0x91, 0x53, 0x31, 0x25, 0x4c, 0xbf, 0x1e, 0xc3, 0x99, 0x90, 0xca,
	0x80, 0xc6, 0xa1, 0x17, 0x2b, 0x53, 0x55, 0xff, 0x89, 0xc8, 0x9f, 0xbe, 0x6c, 0x73, 0x59, 0x07,
	0x01, 0x49, 0x3e, 0x04, 0x92, 0x71, 0x4a, 0x75, 0x9c, 0xed, 0x56, 0x63, 0x61, 0x91, 0x8f, 0x8e,
	0xb1, 0x69, 0x1f, 0xc3, 0xf9, 0x55, 0xb2, 0xcf, 0xc3, 0x99, 0x1b, 0xf8, 0x5c, 0x60, 0x1b, 0xab,
	0xce, 0xd9, 0x4c, 0xc6, 0x90, 0x87, 0xb3, 0x3d, 0x9f, 0x0b, 0x72, 0x0b, 0x2e, 0xae, 0x66, 0xf1,
	0x54, 0x25, 0xa9, 0x72, 0x59, 0x1c, 0xd2, 0x63, 0xec, 0x72, 0xcd, 0x39, 0x97, 0x49, 0xfc, 0x0c,
	0xc3, 0x07, 0x3a, 0xfa, 0x1a, 0xa7, 0xd9, 0x3e, 0x85, 0xd3, 0x94, 0x4e, 0xe1, 0x34, 0xe5, 0x37,
	0x39, 0xcd, 0xf0, 0xe6, 0xd3, 0x93, 0x4e, 0xee, 0xd9, 0x49, 0x27, 0xf7, 0xd7, 0x49, 0x27, 0xf7,
	0xc3, 0x8b, 0xce, 0xc6, 0xb3, 0x17, 0x9d, 0x8d, 0x3f, 0x5e, 0x74, 0x36, 0x1e, 0x77, 0xa8, 0xb6,
	0xf8, 0x84, 0xb3, 0x58, 0xf5, 0x8f, 0xfb, 0x2f, 0xfd, 0x5b, 0xf6, 0x8b, 0xf8, 0xc5, 0xfd, 0xe8,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xd7, 0x5e, 0x58, 0x52, 0x0b, 0x00, 0x00,
}

func (m *Height) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Height) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Height) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevisionHeight != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.RevisionHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.RevisionNumber != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.RevisionNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HeuristicParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeuristicParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeuristicParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StakeWeightBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.StakeWeightBps))
		i--
		dAtA[i] = 0x48
	}
	if m.PoolsWeightBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.PoolsWeightBps))
		i--
		dAtA[i] = 0x40
	}
	if m.DepthWeightBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.DepthWeightBps))
		i--
		dAtA[i] = 0x38
	}
	if m.TargetUniqueStakeBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.TargetUniqueStakeBps))
		i--
		dAtA[i] = 0x30
	}
	if m.TargetUniquePools != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.TargetUniquePools))
		i--
		dAtA[i] = 0x28
	}
	if m.TargetDepth != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.TargetDepth))
		i--
		dAtA[i] = 0x20
	}
	if m.MinUniqueStakeBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.MinUniqueStakeBps))
		i--
		dAtA[i] = 0x18
	}
	if m.MinUniquePools != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.MinUniquePools))
		i--
		dAtA[i] = 0x10
	}
	if m.MinDepth != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.MinDepth))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StakeDistributionEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakeDistributionEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakeDistributionEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stake != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.Stake))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintStability(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EpochStakeDistribution) > 0 {
		for iNdEx := len(m.EpochStakeDistribution) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochStakeDistribution[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStability(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.HostStateNftTokenName) > 0 {
		i -= len(m.HostStateNftTokenName)
		copy(dAtA[i:], m.HostStateNftTokenName)
		i = encodeVarintStability(dAtA, i, uint64(len(m.HostStateNftTokenName)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.HostStateNftPolicyId) > 0 {
		i -= len(m.HostStateNftPolicyId)
		copy(dAtA[i:], m.HostStateNftPolicyId)
		i = encodeVarintStability(dAtA, i, uint64(len(m.HostStateNftPolicyId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.UpgradePath) > 0 {
		for iNdEx := len(m.UpgradePath) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.UpgradePath[iNdEx])
			copy(dAtA[i:], m.UpgradePath[iNdEx])
			i = encodeVarintStability(dAtA, i, uint64(len(m.UpgradePath[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.HeuristicParams != nil {
		{
			size, err := m.HeuristicParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintStability(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if m.CurrentEpoch != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.FrozenHeight != nil {
		{
			size, err := m.FrozenHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.LatestHeight != nil {
		{
			size, err := m.LatestHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintStability(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SecurityScoreBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.SecurityScoreBps))
		i--
		dAtA[i] = 0x38
	}
	if m.UniqueStakeBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.UniqueStakeBps))
		i--
		dAtA[i] = 0x30
	}
	if m.UniquePoolsCount != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.UniquePoolsCount))
		i--
		dAtA[i] = 0x28
	}
	if m.AcceptedEpoch != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.AcceptedEpoch))
		i--
		dAtA[i] = 0x20
	}
	if len(m.AcceptedBlockHash) > 0 {
		i -= len(m.AcceptedBlockHash)
		copy(dAtA[i:], m.AcceptedBlockHash)
		i = encodeVarintStability(dAtA, i, uint64(len(m.AcceptedBlockHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.IbcStateRoot) > 0 {
		i -= len(m.IbcStateRoot)
		copy(dAtA[i:], m.IbcStateRoot)
		i = encodeVarintStability(dAtA, i, uint64(len(m.IbcStateRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.Timestamp != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StabilityHeader2 != nil {
		{
			size, err := m.StabilityHeader2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.StabilityHeader1 != nil {
		{
			size, err := m.StabilityHeader1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintStability(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StabilityBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StabilityBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StabilityBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StakeBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.StakeBps))
		i--
		dAtA[i] = 0x40
	}
	if len(m.SlotLeader) > 0 {
		i -= len(m.SlotLeader)
		copy(dAtA[i:], m.SlotLeader)
		i = encodeVarintStability(dAtA, i, uint64(len(m.SlotLeader)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Timestamp != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.Epoch != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PrevHash) > 0 {
		i -= len(m.PrevHash)
		copy(dAtA[i:], m.PrevHash)
		i = encodeVarintStability(dAtA, i, uint64(len(m.PrevHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintStability(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Slot != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.Slot))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != nil {
		{
			size, err := m.Height.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StabilityHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StabilityHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StabilityHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SecurityScoreBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.SecurityScoreBps))
		i--
		dAtA[i] = 0x48
	}
	if m.UniqueStakeBps != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.UniqueStakeBps))
		i--
		dAtA[i] = 0x40
	}
	if m.UniquePoolsCount != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.UniquePoolsCount))
		i--
		dAtA[i] = 0x38
	}
	if m.HostStateTxOutputIndex != 0 {
		i = encodeVarintStability(dAtA, i, uint64(m.HostStateTxOutputIndex))
		i--
		dAtA[i] = 0x30
	}
	if len(m.HostStateTxBodyCbor) > 0 {
		i -= len(m.HostStateTxBodyCbor)
		copy(dAtA[i:], m.HostStateTxBodyCbor)
		i = encodeVarintStability(dAtA, i, uint64(len(m.HostStateTxBodyCbor)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.HostStateTxHash) > 0 {
		i -= len(m.HostStateTxHash)
		copy(dAtA[i:], m.HostStateTxHash)
		i = encodeVarintStability(dAtA, i, uint64(len(m.HostStateTxHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DescendantBlocks) > 0 {
		for iNdEx := len(m.DescendantBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DescendantBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStability(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AnchorBlock != nil {
		{
			size, err := m.AnchorBlock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TrustedHeight != nil {
		{
			size, err := m.TrustedHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStability(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStability(dAtA []byte, offset int, v uint64) int {
	offset -= sovStability(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Height) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RevisionNumber != 0 {
		n += 1 + sovStability(uint64(m.RevisionNumber))
	}
	if m.RevisionHeight != 0 {
		n += 1 + sovStability(uint64(m.RevisionHeight))
	}
	return n
}

func (m *HeuristicParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinDepth != 0 {
		n += 1 + sovStability(uint64(m.MinDepth))
	}
	if m.MinUniquePools != 0 {
		n += 1 + sovStability(uint64(m.MinUniquePools))
	}
	if m.MinUniqueStakeBps != 0 {
		n += 1 + sovStability(uint64(m.MinUniqueStakeBps))
	}
	if m.TargetDepth != 0 {
		n += 1 + sovStability(uint64(m.TargetDepth))
	}
	if m.TargetUniquePools != 0 {
		n += 1 + sovStability(uint64(m.TargetUniquePools))
	}
	if m.TargetUniqueStakeBps != 0 {
		n += 1 + sovStability(uint64(m.TargetUniqueStakeBps))
	}
	if m.DepthWeightBps != 0 {
		n += 1 + sovStability(uint64(m.DepthWeightBps))
	}
	if m.PoolsWeightBps != 0 {
		n += 1 + sovStability(uint64(m.PoolsWeightBps))
	}
	if m.StakeWeightBps != 0 {
		n += 1 + sovStability(uint64(m.StakeWeightBps))
	}
	return n
}

func (m *StakeDistributionEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.Stake != 0 {
		n += 1 + sovStability(uint64(m.Stake))
	}
	return n
}

func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.LatestHeight != nil {
		l = m.LatestHeight.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if m.FrozenHeight != nil {
		l = m.FrozenHeight.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if m.CurrentEpoch != 0 {
		n += 1 + sovStability(uint64(m.CurrentEpoch))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovStability(uint64(l))
	if m.HeuristicParams != nil {
		l = m.HeuristicParams.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if len(m.UpgradePath) > 0 {
		for _, s := range m.UpgradePath {
			l = len(s)
			n += 1 + l + sovStability(uint64(l))
		}
	}
	l = len(m.HostStateNftPolicyId)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	l = len(m.HostStateNftTokenName)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if len(m.EpochStakeDistribution) > 0 {
		for _, e := range m.EpochStakeDistribution {
			l = e.Size()
			n += 1 + l + sovStability(uint64(l))
		}
	}
	return n
}

func (m *ConsensusState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovStability(uint64(m.Timestamp))
	}
	l = len(m.IbcStateRoot)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	l = len(m.AcceptedBlockHash)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.AcceptedEpoch != 0 {
		n += 1 + sovStability(uint64(m.AcceptedEpoch))
	}
	if m.UniquePoolsCount != 0 {
		n += 1 + sovStability(uint64(m.UniquePoolsCount))
	}
	if m.UniqueStakeBps != 0 {
		n += 1 + sovStability(uint64(m.UniqueStakeBps))
	}
	if m.SecurityScoreBps != 0 {
		n += 1 + sovStability(uint64(m.SecurityScoreBps))
	}
	return n
}

func (m *Misbehaviour) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.StabilityHeader1 != nil {
		l = m.StabilityHeader1.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if m.StabilityHeader2 != nil {
		l = m.StabilityHeader2.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	return n
}

func (m *StabilityBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != nil {
		l = m.Height.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if m.Slot != 0 {
		n += 1 + sovStability(uint64(m.Slot))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	l = len(m.PrevHash)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovStability(uint64(m.Epoch))
	}
	if m.Timestamp != 0 {
		n += 1 + sovStability(uint64(m.Timestamp))
	}
	l = len(m.SlotLeader)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.StakeBps != 0 {
		n += 1 + sovStability(uint64(m.StakeBps))
	}
	return n
}

func (m *StabilityHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustedHeight != nil {
		l = m.TrustedHeight.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if m.AnchorBlock != nil {
		l = m.AnchorBlock.Size()
		n += 1 + l + sovStability(uint64(l))
	}
	if len(m.DescendantBlocks) > 0 {
		for _, e := range m.DescendantBlocks {
			l = e.Size()
			n += 1 + l + sovStability(uint64(l))
		}
	}
	l = len(m.HostStateTxHash)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	l = len(m.HostStateTxBodyCbor)
	if l > 0 {
		n += 1 + l + sovStability(uint64(l))
	}
	if m.HostStateTxOutputIndex != 0 {
		n += 1 + sovStability(uint64(m.HostStateTxOutputIndex))
	}
	if m.UniquePoolsCount != 0 {
		n += 1 + sovStability(uint64(m.UniquePoolsCount))
	}
	if m.UniqueStakeBps != 0 {
		n += 1 + sovStability(uint64(m.UniqueStakeBps))
	}
	if m.SecurityScoreBps != 0 {
		n += 1 + sovStability(uint64(m.SecurityScoreBps))
	}
	return n
}

func sovStability(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStability(x uint64) (n int) {
	return sovStability(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Height) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Height: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Height: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionNumber", wireType)
			}
			m.RevisionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionHeight", wireType)
			}
			m.RevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeuristicParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeuristicParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeuristicParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDepth", wireType)
			}
			m.MinDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDepth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinUniquePools", wireType)
			}
			m.MinUniquePools = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinUniquePools |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinUniqueStakeBps", wireType)
			}
			m.MinUniqueStakeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinUniqueStakeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetDepth", wireType)
			}
			m.TargetDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetDepth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetUniquePools", wireType)
			}
			m.TargetUniquePools = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetUniquePools |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetUniqueStakeBps", wireType)
			}
			m.TargetUniqueStakeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetUniqueStakeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepthWeightBps", wireType)
			}
			m.DepthWeightBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepthWeightBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolsWeightBps", wireType)
			}
			m.PoolsWeightBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolsWeightBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeWeightBps", wireType)
			}
			m.StakeWeightBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakeWeightBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakeDistributionEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakeDistributionEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakeDistributionEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stake", wireType)
			}
			m.Stake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestHeight == nil {
				m.LatestHeight = &Height{}
			}
			if err := m.LatestHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrozenHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FrozenHeight == nil {
				m.FrozenHeight = &Height{}
			}
			if err := m.FrozenHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeuristicParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HeuristicParams == nil {
				m.HeuristicParams = &HeuristicParams{}
			}
			if err := m.HeuristicParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpgradePath = append(m.UpgradePath, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateNftPolicyId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateNftPolicyId = append(m.HostStateNftPolicyId[:0], dAtA[iNdEx:postIndex]...)
			if m.HostStateNftPolicyId == nil {
				m.HostStateNftPolicyId = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateNftTokenName", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateNftTokenName = append(m.HostStateNftTokenName[:0], dAtA[iNdEx:postIndex]...)
			if m.HostStateNftTokenName == nil {
				m.HostStateNftTokenName = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStakeDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochStakeDistribution = append(m.EpochStakeDistribution, &StakeDistributionEntry{})
			if err := m.EpochStakeDistribution[len(m.EpochStakeDistribution)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcStateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcStateRoot = append(m.IbcStateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcStateRoot == nil {
				m.IbcStateRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedEpoch", wireType)
			}
			m.AcceptedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcceptedEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniquePoolsCount", wireType)
			}
			m.UniquePoolsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniquePoolsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueStakeBps", wireType)
			}
			m.UniqueStakeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniqueStakeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityScoreBps", wireType)
			}
			m.SecurityScoreBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecurityScoreBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Misbehaviour) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Misbehaviour: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Misbehaviour: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StabilityHeader1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StabilityHeader1 == nil {
				m.StabilityHeader1 = &StabilityHeader{}
			}
			if err := m.StabilityHeader1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StabilityHeader2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StabilityHeader2 == nil {
				m.StabilityHeader2 = &StabilityHeader{}
			}
			if err := m.StabilityHeader2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StabilityBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StabilityBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StabilityBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Height == nil {
				m.Height = &Height{}
			}
			if err := m.Height.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotLeader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlotLeader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeBps", wireType)
			}
			m.StakeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StabilityHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStability
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StabilityHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StabilityHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustedHeight == nil {
				m.TrustedHeight = &Height{}
			}
			if err := m.TrustedHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnchorBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AnchorBlock == nil {
				m.AnchorBlock = &StabilityBlock{}
			}
			if err := m.AnchorBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DescendantBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DescendantBlocks = append(m.DescendantBlocks, &StabilityBlock{})
			if err := m.DescendantBlocks[len(m.DescendantBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateTxBodyCbor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStability
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStability
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostStateTxBodyCbor = append(m.HostStateTxBodyCbor[:0], dAtA[iNdEx:postIndex]...)
			if m.HostStateTxBodyCbor == nil {
				m.HostStateTxBodyCbor = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostStateTxOutputIndex", wireType)
			}
			m.HostStateTxOutputIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HostStateTxOutputIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniquePoolsCount", wireType)
			}
			m.UniquePoolsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniquePoolsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueStakeBps", wireType)
			}
			m.UniqueStakeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UniqueStakeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityScoreBps", wireType)
			}
			m.SecurityScoreBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStability
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecurityScoreBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStability(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStability
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStability(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStability
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStability
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStability
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStability
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStability
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStability
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStability        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStability          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStability = fmt.Errorf("proto: unexpected end of group")
)
