version: 1
accounts:
  - name: entrypoint-relayer
    mnemonic: engage vote never tired enter brain chat loan coil venture soldier shine awkward keen delay link mass print venue federal ankle valid upgrade balance
  - name: injective-local-validator
    mnemonic: bottom loan skill merry east cradle onion journey palm apology verb edit desert impose absurd oil bubble sweet glove shallow size build burst effort
  - name: injective-local-relayer
    mnemonic: bottom loan skill merry east cradle onion journey palm apology verb edit desert impose absurd oil bubble sweet glove shallow size build burst effort
