services:
  cardano-node:
    image: ${CARDANO_NODE_IMAGE:-ghcr.io/blinklabs-io/cardano-node:10.1.4-3}
    container_name: cardano-node
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./${CARDANO_RUNTIME_DIR:-devnet}:/runtime
      - ./run-cardano-node.sh:/run-cardano-node.sh:ro
    environment:
      - CARDANO_BLOCK_PRODUCER=${CARDANO_BLOCK_PRODUCER:-true}
      - CARDANO_RUNTIME_CONFIG_FILE=${CARDANO_NODE_CONFIG_FILE:-cardano-node.json}
      - CARDANO_RUNTIME_TOPOLOGY_FILE=${CARDANO_TOPOLOGY_FILE:-topology.json}
      - CARDANO_SOCKET_PATH=/runtime/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/runtime/node.socket # used by cardano-cli
      - RESTORE_SNAPSHOT=false
    ports:
      - 3001:3001
    entrypoint: ["/bin/sh", "/run-cardano-node.sh"]

  cardano-node-ogmios:
    image: cardanosolutions/ogmios:v6.10.0
    user: "${UID:-1000}:${GID:-1000}"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    depends_on:
      - cardano-node
    volumes:
      - ./${CARDANO_RUNTIME_DIR:-devnet}:/runtime
      - ./${CARDANO_RUNTIME_DIR:-devnet}/db:/db
    command:
      [
        "--node-config",
        "/runtime/${CARDANO_NODE_CONFIG_FILE:-cardano-node.json}",
        "--host",
        "0.0.0.0",
        "--node-socket",
        "/runtime/node.socket"
      ]

  kupo:
    image: cardanosolutions/kupo:v2.9.0
    user: "${UID:-1000}:${GID:-1000}"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    depends_on:
      - cardano-node
    ports:
      - ${KUPO_PORT:-1442}:1442
    command:
      [
        "--node-socket",
        "/runtime/node.socket",
        "--node-config",
        "/runtime/${CARDANO_NODE_CONFIG_FILE:-cardano-node.json}",
        "--since",
        "${KUPO_SINCE:-origin}",
        "--match",
        "${KUPO_MATCH:-*}",
        "--workdir",
        "/db",
        "--host",
        "0.0.0.0",
        "--port",
        "1442"
      ]
    volumes:
      - ./${CARDANO_RUNTIME_DIR:-devnet}:/runtime
      - ./kupo-db:/db

  postgres:
    image: postgres:15
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - ${POSTGRES_PORT:-6432}:5432
    depends_on:
      - cardano-node
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      # Use pg_isready to check postgres is running. Substitute different
      # user `postgres` if you've setup differently to config/pgpass-mainnet
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ${POSTGRES_ARGS:--c maintenance_work_mem=1GB -c max_parallel_maintenance_workers=4}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: ${CARDANO_DB_SYNC_IMAGE:-ghcr.io/blinklabs-io/cardano-db-sync:main@sha256:04b04848fb062e8993a39da863a87cb9863de1bc4cd3baf0a84b60a7b772d8f7}
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_RECREATE_DB=N
      - CARDANO_NODE_SOCKET_PATH=/runtime/node.socket
      - NETWORK=${CARDANO_DB_SYNC_NETWORK:-devnet}
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./${CARDANO_RUNTIME_DIR:-devnet}:/runtime
      - ./db-sync-data:/var/lib/cexplorer
      - ./db-sync-configuration:/configuration
      - ./db-sync-log-dir:/log-dir
    command:
      [
        "--config",
        "/runtime/${CARDANO_DB_SYNC_CONFIG_FILE:-db-sync-config.json}"
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    name: cardano_ibc_net

secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user
