services:
  postgres:
    image: postgres:14.10-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - ${POSTGRES_PORT:-6432}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      # Use pg_isready to check postgres is running. Substitute different
      # user `postgres` if you've setup differently to config/pgpass-mainnet
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ${POSTGRES_ARGS:--c maintenance_work_mem=1GB -c max_parallel_maintenance_workers=4}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # cardano-db-sync:
  #   image: ghcr.io/blinklabs-io/cardano-db-sync:main
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - RESTORE_RECREATE_DB=N
  #     - CARDANO_NODE_SOCKET_PATH=/opt/cardano/config/devnet/node.socket
  #     - NETWORK=devnet
  #   depends_on:
  #     - cardano-node
  #     - postgres
  #   secrets:
  #     - postgres_password
  #     - postgres_user
  #     - postgres_db
  #   volumes:
  #     - ./devnet:/opt/cardano/config/devnet
  #     - ./db-sync-data:/var/lib/cexplorer
  #   command:
  #     [
  #       "--config",
  #       "/devnet/db-sync-config.json"
  #     ]
  #   restart: on-failure
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"

secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user
